# Generated 46 rows
SEED_PLUGIN_BOARD_REGISTRY: List[Dict[str, Any]] = [
    {
        "sr_no": 1,
        "plugin_name": 'Post SMTP Free',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/POSTSMTP/boards/132/backlog',
        "internal_support_board": 'https://objectsws.atlassian.net/jira/software/projects/SMTPSUPORT/boards/131',
        "service_management_board": 'https://objectsws.atlassian.net/browse/POST',
        "internal_project_key": 'POSTSMTP',
        "support_project_key": 'SMTPSUPORT',
        "service_management_project_key": 'POST',
    },
    {
        "sr_no": 2,
        "plugin_name": 'Post SMTP Addons',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/POSTSMTP/boards/132/backlog',
        "internal_support_board": 'https://objectsws.atlassian.net/jira/software/projects/SMTPSUPORT/boards/131',
        "service_management_board": 'https://objectsws.atlassian.net/browse/POST',
        "internal_project_key": 'POSTSMTP',
        "support_project_key": 'SMTPSUPORT',
        "service_management_project_key": 'POST',
    },
    {
        "sr_no": 3,
        "plugin_name": 'Post SMTP Mobile App',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/PSA/boards/172/backlog',
        "internal_support_board": 'https://objectsws.atlassian.net/jira/software/projects/SMTPSUPORT/boards/131',
        "service_management_board": 'https://objectsws.atlassian.net/browse/POST',
        "internal_project_key": 'PSA',
        "support_project_key": 'SMTPSUPORT',
        "service_management_project_key": 'POST',
    },
    {
        "sr_no": 4,
        "plugin_name": 'MainWP Post SMTP ORG',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/PSMEL/boards/116/',
        "internal_support_board": 'https://objectsws.atlassian.net/jira/software/projects/SMTPSUPORT/boards/131',
        "service_management_board": 'https://objectsws.atlassian.net/browse/POST',
        "internal_project_key": 'PSMEL',
        "support_project_key": 'SMTPSUPORT',
        "service_management_project_key": 'POST',
    },
    {
        "sr_no": 5,
        "plugin_name": 'AFM',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/AFM/boards/211/backlog',
        "internal_support_board": 'https://objectsws.atlassian.net/jira/software/projects/AFMIS/boards/216',
        "service_management_board": 'https://objectsws.atlassian.net/browse/AFMS',
        "internal_project_key": 'AFM',
        "support_project_key": 'AFMIS',
        "service_management_project_key": 'AFMS',
    },
    {
        "sr_no": 6,
        "plugin_name": 'Gutena Forms',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/GF/boards/1281/backlog',
        "internal_support_board": 'https://objectsws.atlassian.net/jira/software/projects/GFIS/boards/1282',
        "service_management_board": 'https://objectsws.atlassian.net/browse/GFS',
        "internal_project_key": 'GF',
        "support_project_key": 'GFIS',
        "service_management_project_key": 'GFS',
    },
    {
        "sr_no": 7,
        "plugin_name": 'AIO Login',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/AIOL/boards/179',
        "internal_support_board": 'https://objectsws.atlassian.net/jira/software/projects/AIOLAIS/boards/202',
        "service_management_board": 'https://objectsws.atlassian.net/browse/AIOS',
        "internal_project_key": 'AIOL',
        "support_project_key": 'AIOLAIS',
        "service_management_project_key": 'AIOS',
    },
    {
        "sr_no": 8,
        "plugin_name": 'SMTP & Email Logs',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/SEL/boards/952',
        "internal_support_board": 'No Board',
        "service_management_board": 'https://objectsws.atlassian.net/browse/SELS',
        "internal_project_key": 'SEL',
        "support_project_key": None,
        "service_management_project_key": 'SELS',
    },
    {
        "sr_no": 9,
        "plugin_name": 'Quick Contact Form',
        "internal_board": 'No Board',
        "internal_support_board": 'No Board',
        "service_management_board": 'No Board',
        "internal_project_key": None,
        "support_project_key": None,
        "service_management_project_key": None,
    },
    {
        "sr_no": 10,
        "plugin_name": 'WC Shop Sync Free',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/WSF/boards/161',
        "internal_support_board": 'https://objectsws.atlassian.net/jira/software/projects/WSSS/boards/178',
        "service_management_board": 'https://objectsws.atlassian.net/browse/WSPLUSSUP',
        "internal_project_key": 'WSF',
        "support_project_key": 'WSSS',
        "service_management_project_key": 'WSPLUSSUP',
    },
    {
        "sr_no": 11,
        "plugin_name": 'WC Shop Sync Pro',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/WP/boards/88',
        "internal_support_board": 'https://objectsws.atlassian.net/jira/software/projects/WSSS/boards/178',
        "service_management_board": 'https://objectsws.atlassian.net/browse/WSPLUSSUP',
        "internal_project_key": 'WP',
        "support_project_key": 'WSSS',
        "service_management_project_key": 'WSPLUSSUP',
    },
    {
        "sr_no": 12,
        "plugin_name": 'WC Square Recurring Payments',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/WP/boards/88',
        "internal_support_board": 'https://objectsws.atlassian.net/jira/software/projects/WSSS/boards/178',
        "service_management_board": 'https://objectsws.atlassian.net/browse/SIA',
        "internal_project_key": 'WP',
        "support_project_key": 'WSSS',
        "service_management_project_key": 'SIA',
    },
    {
        "sr_no": 13,
        "plugin_name": 'Woocommerce Booking Exporter',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/WBE/boards/155',
        "internal_support_board": 'No Board',
        "service_management_board": 'https://objectsws.atlassian.net/browse/WPS',
        "internal_project_key": 'WBE',
        "support_project_key": None,
        "service_management_project_key": 'WPS',
    },
    {
        "sr_no": 14,
        "plugin_name": 'WP Multi Store Locator',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/MULTILOCAT/boards/91/backlog',
        "internal_support_board": 'No Board',
        "service_management_board": 'https://objectsws.atlassian.net/browse/WPS',
        "internal_project_key": 'MULTILOCAT',
        "support_project_key": None,
        "service_management_project_key": 'WPS',
    },
    {
        "sr_no": 15,
        "plugin_name": 'Gravity Square',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/SQPST/boards/101/backlog',
        "internal_support_board": 'https://objectsws.atlassian.net/jira/software/projects/PGC/boards/85/backlog',
        "service_management_board": 'https://objectsws.atlassian.net/browse/SIA',
        "internal_project_key": 'SQPST',
        "support_project_key": 'PGC',
        "service_management_project_key": 'SIA',
    },
    {
        "sr_no": 16,
        "plugin_name": 'Formidible Square',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/SQPST/boards/101/backlog',
        "internal_support_board": 'https://objectsws.atlassian.net/jira/software/projects/PGC/boards/85/backlog',
        "service_management_board": 'https://objectsws.atlassian.net/browse/SIA',
        "internal_project_key": 'SQPST',
        "support_project_key": 'PGC',
        "service_management_project_key": 'SIA',
    },
    {
        "sr_no": 17,
        "plugin_name": 'Memberpress Square',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/SQPST/boards/101/backlog',
        "internal_support_board": 'https://objectsws.atlassian.net/jira/software/projects/PGC/boards/85/backlog',
        "service_management_board": 'https://objectsws.atlassian.net/browse/SIA',
        "internal_project_key": 'SQPST',
        "support_project_key": 'PGC',
        "service_management_project_key": 'SIA',
    },
    {
        "sr_no": 18,
        "plugin_name": 'WP Form Square',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/SQPST/boards/101/backlog',
        "internal_support_board": 'https://objectsws.atlassian.net/jira/software/projects/PGC/boards/85/backlog',
        "service_management_board": 'https://objectsws.atlassian.net/browse/SIA',
        "internal_project_key": 'SQPST',
        "support_project_key": 'PGC',
        "service_management_project_key": 'SIA',
    },
    {
        "sr_no": 19,
        "plugin_name": 'Ninja Square',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/SQPST/boards/101/backlog',
        "internal_support_board": 'https://objectsws.atlassian.net/jira/software/projects/PGC/boards/85/backlog',
        "service_management_board": 'https://objectsws.atlassian.net/browse/SIA',
        "internal_project_key": 'SQPST',
        "support_project_key": 'PGC',
        "service_management_project_key": 'SIA',
    },
    {
        "sr_no": 20,
        "plugin_name": 'Give Square',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/SQPST/boards/101/backlog',
        "internal_support_board": 'https://objectsws.atlassian.net/jira/software/projects/PGC/boards/85/backlog',
        "service_management_board": 'https://objectsws.atlassian.net/browse/SIA',
        "internal_project_key": 'SQPST',
        "support_project_key": 'PGC',
        "service_management_project_key": 'SIA',
    },
    {
        "sr_no": 21,
        "plugin_name": 'Gravity World Pay Square',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/SQPST/boards/101/backlog',
        "internal_support_board": 'https://objectsws.atlassian.net/jira/software/projects/PGC/boards/85/backlog',
        "service_management_board": 'https://objectsws.atlassian.net/browse/SIA',
        "internal_project_key": 'SQPST',
        "support_project_key": 'PGC',
        "service_management_project_key": 'SIA',
    },
    {
        "sr_no": 22,
        "plugin_name": 'SumUp Payment Gateway',
        "internal_board": 'No Board',
        "internal_support_board": 'No Board',
        "service_management_board": 'No Board',
        "internal_project_key": None,
        "support_project_key": None,
        "service_management_project_key": None,
    },
    {
        "sr_no": 23,
        "plugin_name": 'WP Contact Slider',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/WPCS/boards/183',
        "internal_support_board": 'No Board',
        "service_management_board": 'https://objectsws.atlassian.net/browse/WPCSS',
        "internal_project_key": 'WPCS',
        "support_project_key": None,
        "service_management_project_key": 'WPCSS',
    },
    {
        "sr_no": 24,
        "plugin_name": 'Password Protected',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/PP/boards/117',
        "internal_support_board": 'https://objectsws.atlassian.net/jira/software/projects/PPIS/boards/195',
        "service_management_board": 'https://objectsws.atlassian.net/browse/PAS',
        "internal_project_key": 'PP',
        "support_project_key": 'PPIS',
        "service_management_project_key": 'PAS',
    },
    {
        "sr_no": 25,
        "plugin_name": 'WP EasyPay Free',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/WEPF/boards/174/backlog',
        "internal_support_board": 'https://objectsws.atlassian.net/jira/software/projects/WEPIS/boards/190/backlog',
        "service_management_board": 'https://objectsws.atlassian.net/browse/WPEPSUP',
        "internal_project_key": 'WEPF',
        "support_project_key": 'WEPIS',
        "service_management_project_key": 'WPEPSUP',
    },
    {
        "sr_no": 26,
        "plugin_name": 'WP EasyPay Pro',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/WPEP/boards/40/backlog',
        "internal_support_board": 'https://objectsws.atlassian.net/jira/software/projects/WEPIS/boards/190/backlog',
        "service_management_board": 'https://objectsws.atlassian.net/browse/WPEPSUP',
        "internal_project_key": 'WPEP',
        "support_project_key": 'WEPIS',
        "service_management_project_key": 'WPEPSUP',
    },
    {
        "sr_no": 27,
        "plugin_name": 'CF7 Apps',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/HFCF7/boards/196/backlog',
        "internal_support_board": 'https://objectsws.atlassian.net/jira/software/projects/HPCF7IS/boards/223/backlog',
        "service_management_board": 'https://objectsws.atlassian.net/browse/CA',
        "internal_project_key": 'HFCF7',
        "support_project_key": 'HPCF7IS',
        "service_management_project_key": 'CA',
    },
    {
        "sr_no": 28,
        "plugin_name": 'Gutena Accordion – Beautiful FAQ Accordion Block',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/GUT/boards/1347/backlog',
        "internal_support_board": 'No Board',
        "service_management_board": 'https://objectsws.atlassian.net/browse/GFS',
        "internal_project_key": 'GUT',
        "support_project_key": None,
        "service_management_project_key": 'GFS',
    },
    {
        "sr_no": 29,
        "plugin_name": 'Gutena Kit',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/GUT/boards/1347/backlog',
        "internal_support_board": 'No Board',
        "service_management_board": 'https://objectsws.atlassian.net/browse/GFS',
        "internal_project_key": 'GUT',
        "support_project_key": None,
        "service_management_project_key": 'GFS',
    },
    {
        "sr_no": 30,
        "plugin_name": 'Gutena Newsletter',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/GUT/boards/1347/backlog',
        "internal_support_board": 'No Board',
        "service_management_board": 'https://objectsws.atlassian.net/browse/GFS',
        "internal_project_key": 'GUT',
        "support_project_key": None,
        "service_management_project_key": 'GFS',
    },
    {
        "sr_no": 31,
        "plugin_name": 'Gutena PhotoFeed',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/GUT/boards/1347/backlog',
        "internal_support_board": 'No Board',
        "service_management_board": 'https://objectsws.atlassian.net/browse/GFS',
        "internal_project_key": 'GUT',
        "support_project_key": None,
        "service_management_project_key": 'GFS',
    },
    {
        "sr_no": 32,
        "plugin_name": 'Gutena Recent Post Custom Tag',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/GUT/boards/1347/backlog',
        "internal_support_board": 'No Board',
        "service_management_board": 'https://objectsws.atlassian.net/browse/GFS',
        "internal_project_key": 'GUT',
        "support_project_key": None,
        "service_management_project_key": 'GFS',
    },
    {
        "sr_no": 33,
        "plugin_name": 'Gutena Star Ratings',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/GUT/boards/1347/backlog',
        "internal_support_board": 'No Board',
        "service_management_board": 'https://objectsws.atlassian.net/browse/GFS',
        "internal_project_key": 'GUT',
        "support_project_key": None,
        "service_management_project_key": 'GFS',
    },
    {
        "sr_no": 34,
        "plugin_name": 'Gutena Tabs',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/GUT/boards/1347/backlog',
        "internal_support_board": 'No Board',
        "service_management_board": 'https://objectsws.atlassian.net/browse/GFS',
        "internal_project_key": 'GUT',
        "support_project_key": None,
        "service_management_project_key": 'GFS',
    },
    {
        "sr_no": 35,
        "plugin_name": 'Gutena Team',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/GUT/boards/1347/backlog',
        "internal_support_board": 'No Board',
        "service_management_board": 'https://objectsws.atlassian.net/browse/GFS',
        "internal_project_key": 'GUT',
        "support_project_key": None,
        "service_management_project_key": 'GFS',
    },
    {
        "sr_no": 36,
        "plugin_name": 'Gutena Testimonial Slider',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/GUT/boards/1347/backlog',
        "internal_support_board": 'No Board',
        "service_management_board": 'https://objectsws.atlassian.net/browse/GFS',
        "internal_project_key": 'GUT',
        "support_project_key": None,
        "service_management_project_key": 'GFS',
    },
    {
        "sr_no": 37,
        "plugin_name": 'Gutena Video Lightbox',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/GUT/boards/1347/backlog',
        "internal_support_board": 'No Board',
        "service_management_board": 'https://objectsws.atlassian.net/browse/GFS',
        "internal_project_key": 'GUT',
        "support_project_key": None,
        "service_management_project_key": 'GFS',
    },
    {
        "sr_no": 38,
        "plugin_name": 'OGTag',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/OGTCT/boards/143/backlog',
        "internal_support_board": 'No Board',
        "service_management_board": 'https://objectsws.atlassian.net/browse/WPS',
        "internal_project_key": 'OGTCT',
        "support_project_key": None,
        "service_management_project_key": 'WPS',
    },
    {
        "sr_no": 39,
        "plugin_name": 'Login Designer',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/LD/boards/113/backlog',
        "internal_support_board": 'No Board',
        "service_management_board": 'https://objectsws.atlassian.net/browse/LDSB',
        "internal_project_key": 'LD',
        "support_project_key": None,
        "service_management_project_key": 'LDSB',
    },
    {
        "sr_no": 40,
        "plugin_name": 'WP Formify  (Discontinue)',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/WPF/boards/786/backlog',
        "internal_support_board": 'No Board',
        "service_management_board": 'https://objectsws.atlassian.net/browse/WPS',
        "internal_project_key": 'WPF',
        "support_project_key": None,
        "service_management_project_key": 'WPS',
    },
    {
        "sr_no": 41,
        "plugin_name": 'Custom Product Builder',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/VPD/boards/3547/backlog',
        "internal_support_board": 'https://objectsws.atlassian.net/jira/software/projects/VPDIS/boards/3548/backlog',
        "service_management_board": 'https://objectsws.atlassian.net/browse/VPDSSM',
        "internal_project_key": 'VPD',
        "support_project_key": 'VPDIS',
        "service_management_project_key": 'VPDSSM',
    },
    {
        "sr_no": 42,
        "plugin_name": 'NOWPayments',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/CDP/boards/3585/backlog',
        "internal_support_board": 'https://objectsws.atlassian.net/jira/software/projects/CIS/boards/4819/backlog',
        "service_management_board": 'https://objectsws.atlassian.net/browse/CPS',
        "internal_project_key": 'CDP',
        "support_project_key": 'CIS',
        "service_management_project_key": 'CPS',
    },
    {
        "sr_no": 43,
        "plugin_name": 'Coinbase Commerce',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/CDP/boards/3585/backlog',
        "internal_support_board": 'https://objectsws.atlassian.net/jira/software/projects/CIS/boards/4819/backlog',
        "service_management_board": 'https://objectsws.atlassian.net/browse/CPS',
        "internal_project_key": 'CDP',
        "support_project_key": 'CIS',
        "service_management_project_key": 'CPS',
    },
    {
        "sr_no": 44,
        "plugin_name": 'CF7 Booking',
        "internal_board": 'No Board',
        "internal_support_board": 'No Board',
        "service_management_board": 'No Board',
        "internal_project_key": None,
        "support_project_key": None,
        "service_management_project_key": None,
    },
    {
        "sr_no": 55,
        "plugin_name": 'Marketing Board',
        "internal_board": 'https://objectsws.atlassian.net/jira/software/projects/TREN/boards/207/backlog',
        "internal_support_board": None,
        "service_management_board": None,
        "internal_project_key": 'TREN',
        "support_project_key": None,
        "service_management_project_key": None,
    },
    {
        "sr_no": 56,
        "plugin_name": 'Trend Alliance Management',
        "internal_board": 'https://objectsws.atlassian.net/jira/core/projects/TAM/board?filter=&groupBy=none',
        "internal_support_board": None,
        "service_management_board": None,
        "internal_project_key": 'TAM',
        "support_project_key": None,
        "service_management_project_key": None,
    },
]
