"""Discord rich embed message formatter."""

from typing import Any, Dict, List, Optional
from app.utils.time import utc_now_iso
from app.config.settings import settings


# Centralized Standardized Discord Color Constants (Decimal)
COLOR_ASSIGNMENT = 3066993      # #2ECC71 - Green (Assignment to me)
COLOR_NOTIFICATION = 3447003    # #3498DB - Blue (Mention / General notification)
COLOR_WORKLOG = 10181046        # #9B59B6 - Purple (Worklog / Reports)
COLOR_OVERDUE = 15158332        # #E74C3C - Red (Overdue, Blocked, Errors)
COLOR_ATTENTION = 15844367      # #F1C40F - Yellow (PM Attention, Stale, Warnings)
COLOR_TICKET_CREATED = 14689374 # #E0245E - Dark Pink / Red (Ticket Creation Notifications)

# Backwards compatibility aliases
COLOR_GREEN = COLOR_ASSIGNMENT
COLOR_BLUE = COLOR_NOTIFICATION
COLOR_PURPLE = COLOR_WORKLOG
COLOR_RED = COLOR_OVERDUE
COLOR_AMBER = COLOR_ATTENTION
COLOR_MAGENTA = COLOR_ATTENTION
COLOR_DARK_PINK = COLOR_TICKET_CREATED



class DiscordFormatter:
    """Formats notifications and events into Discord Webhook embed payloads."""

    @staticmethod
    def format_jira_link(task_key: str, label: Optional[str] = None) -> str:
        """Construct a clickable markdown link for Jira issues."""
        url = settings.get_jira_browse_url(task_key)
        display_label = label or task_key
        return f"[{display_label}]({url})"

    @staticmethod
    def format_embed(
        title: str,
        description: str,
        color: int = COLOR_BLUE,
        fields: Optional[List[Dict[str, Any]]] = None,
        footer_text: str = "Generated by PM Operations Agent",
        timestamp: Optional[str] = None,
        url: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Construct a Discord Webhook payload with a rich embed."""
        embed: Dict[str, Any] = {
            "title": title,
            "description": description,
            "color": color,
            "footer": {"text": footer_text},
            "timestamp": timestamp or utc_now_iso()
        }
        if url:
            embed["url"] = url
        if fields:
            embed["fields"] = fields

        return {"embeds": [embed]}

    @classmethod
    def format_status_reply(cls, issue_data: Dict[str, Any]) -> str:
        """Format a concise plain-text/markdown status reply for /pm status."""
        key = issue_data.get("key", "")
        fields = issue_data.get("fields", {})
        summary = fields.get("summary", "Untitled")
        status_name = fields.get("status", {}).get("name", "Unknown") if isinstance(fields.get("status"), dict) else str(fields.get("status") or "Unknown")
        assignee_data = fields.get("assignee")
        if isinstance(assignee_data, dict):
            assignee_name = assignee_data.get("displayName", "Unassigned")
        else:
            assignee_name = str(assignee_data or "Unassigned")
        priority_data = fields.get("priority")
        if isinstance(priority_data, dict):
            priority_name = priority_data.get("name", "None")
        else:
            priority_name = str(priority_data or "None")
        due_date = fields.get("duedate") or fields.get("due_date") or "None"

        return (
            f"📋 **{key}**: {summary}\n"
            f"• **Status:** {status_name}\n"
            f"• **Assignee:** {assignee_name}\n"
            f"• **Priority:** {priority_name}\n"
            f"• **Due:** {due_date}"
        )

    @classmethod
    def format_workflow_violation(
        cls,
        task_key: str,
        task_title: str,
        resource_name: str,
        project_name: str,
        details: str,
        timestamp: Optional[str] = None
    ) -> Dict[str, Any]:
        """Format a PM workflow violation alert."""
        issue_link = cls.format_jira_link(task_key)
        jira_url = settings.get_jira_browse_url(task_key)
        fields = [
            {"name": "Issue", "value": issue_link, "inline": True},
            {"name": "Project", "value": project_name or "N/A", "inline": True},
            {"name": "Resource", "value": resource_name or "Unassigned", "inline": True},
            {"name": "Title", "value": task_title or "Untitled", "inline": False},
            {"name": "Issue Details", "value": details, "inline": False},
        ]
        return cls.format_embed(
            title=f"🚨 Jira Workflow Alert — {task_key}",
            description=f"Activity detected on {issue_link} while remaining in **To Do**.",
            color=COLOR_RED,
            fields=fields,
            timestamp=timestamp,
            url=jira_url
        )

    @classmethod
    def format_stale_task(
        cls,
        task_key: str,
        task_title: str,
        assignee_name: str,
        hours_inactive: float,
        timestamp: Optional[str] = None
    ) -> Dict[str, Any]:
        """Format a stale task warning."""
        issue_link = cls.format_jira_link(task_key)
        jira_url = settings.get_jira_browse_url(task_key)
        fields = [
            {"name": "Issue", "value": issue_link, "inline": True},
            {"name": "Assigned to", "value": assignee_name or "Unassigned", "inline": True},
            {"name": "Inactivity", "value": f"{hours_inactive:.1f} hours", "inline": True},
            {"name": "Title", "value": task_title or "Untitled", "inline": False},
        ]
        return cls.format_embed(
            title=f"⚠️ Stale Task Alert — {task_key}",
            description=f"Task {issue_link} has been In Progress for >{int(hours_inactive)}h without activity.",
            color=COLOR_AMBER,
            fields=fields,
            timestamp=timestamp,
            url=jira_url
        )

    @classmethod
    def format_overdue_task(
        cls,
        task_key: str,
        task_title: str,
        assignee_name: str,
        due_date: str,
        current_status: str,
        timestamp: Optional[str] = None
    ) -> Dict[str, Any]:
        """Format an overdue task alert."""
        issue_link = cls.format_jira_link(task_key)
        jira_url = settings.get_jira_browse_url(task_key)
        fields = [
            {"name": "Issue", "value": issue_link, "inline": True},
            {"name": "Assignee", "value": assignee_name or "Unassigned", "inline": True},
            {"name": "Status", "value": current_status, "inline": True},
            {"name": "Due Date", "value": due_date, "inline": True},
            {"name": "Title", "value": task_title or "Untitled", "inline": False},
        ]
        return cls.format_embed(
            title=f"⏰ Overdue Task Alert — {task_key}",
            description=f"Task {issue_link} passed its due date ({due_date}) and is not Done.",
            color=COLOR_OVERDUE,
            fields=fields,
            timestamp=timestamp,
            url=jira_url
        )

    @classmethod
    def format_reopened_task(
        cls,
        task_key: str,
        task_title: str,
        reopened_by: str,
        prev_status: str,
        new_status: str,
        timestamp: Optional[str] = None
    ) -> Dict[str, Any]:
        """Format a reopened task alert."""
        issue_link = cls.format_jira_link(task_key)
        jira_url = settings.get_jira_browse_url(task_key)
        fields = [
            {"name": "Issue", "value": issue_link, "inline": True},
            {"name": "Reopened by", "value": reopened_by or "Unknown", "inline": True},
            {"name": "Transition", "value": f"`{prev_status}` ➔ `{new_status}`", "inline": True},
            {"name": "Title", "value": task_title or "Untitled", "inline": False},
        ]
        return cls.format_embed(
            title=f"🔄 Task Reopened Alert — {task_key}",
            description=f"Task {issue_link} was reopened from **{prev_status}** to **{new_status}**.",
            color=COLOR_BLUE,
            fields=fields,
            timestamp=timestamp,
            url=jira_url
        )

    @classmethod
    def format_task_comment(
        cls,
        task_key: str,
        task_title: str,
        author_name: str,
        comment_body: str,
        task_status: str,
        timestamp: Optional[str] = None
    ) -> Dict[str, Any]:
        """Format a general comment notification alert."""
        issue_link = cls.format_jira_link(task_key)
        jira_url = settings.get_jira_browse_url(task_key)
        preview = comment_body if len(comment_body) <= 400 else comment_body[:397] + "..."
        fields = [
            {"name": "Issue", "value": issue_link, "inline": True},
            {"name": "Status", "value": task_status or "Unknown", "inline": True},
            {"name": "Author", "value": author_name or "Unknown", "inline": True},
            {"name": "Title", "value": task_title or "Untitled", "inline": False},
            {"name": "Comment", "value": preview or "(empty)", "inline": False},
        ]
        return cls.format_embed(
            title=f"💬 Jira Comment Added — {task_key}",
            description=f"New comment posted on {issue_link} by **{author_name or 'Unknown'}**.",
            color=COLOR_BLUE,
            fields=fields,
            timestamp=timestamp,
            url=jira_url
        )

    @classmethod
    def format_task_mention(
        cls,
        task_key: str,
        task_title: str,
        author_name: str,
        comment_body: str,
        task_status: str,
        timestamp: Optional[str] = None
    ) -> Dict[str, Any]:
        """Format a high-priority personal mention notification alert."""
        issue_link = cls.format_jira_link(task_key)
        jira_url = settings.get_jira_browse_url(task_key)
        preview = comment_body if len(comment_body) <= 500 else comment_body[:497] + "..."
        fields = [
            {"name": "Issue", "value": issue_link, "inline": True},
            {"name": "Status", "value": task_status or "Unknown", "inline": True},
            {"name": "Mentioned by", "value": author_name or "Unknown", "inline": True},
            {"name": "Title", "value": task_title or "Untitled", "inline": False},
            {"name": "Comment", "value": preview or "(empty)", "inline": False},
        ]
        return cls.format_embed(
            title=f"🔔 You were mentioned on {task_key}",
            description=f"**{author_name or 'Someone'}** mentioned you in a comment on {issue_link}.",
            color=COLOR_AMBER,
            fields=fields,
            timestamp=timestamp,
            url=jira_url
        )

    @classmethod
    def format_task_assigned(
        cls,
        task_key: str,
        task_title: str,
        new_assignee_name: str,
        old_assignee_name: Optional[str] = None,
        assigned_by: Optional[str] = None,
        is_assigned_to_me: bool = False,
        timestamp: Optional[str] = None
    ) -> Dict[str, Any]:
        """Format a ticket assignment notification."""
        issue_link = cls.format_jira_link(task_key)
        jira_url = settings.get_jira_browse_url(task_key)
        
        if is_assigned_to_me:
            title = f"🎯 Task Assigned to You — {task_key}"
            desc = f"You have been assigned to task {issue_link}."
            color = COLOR_GREEN
        else:
            title = f"👤 Task Assigned — {task_key}"
            desc = f"Task {issue_link} was assigned to **{new_assignee_name or 'Unassigned'}**."
            color = COLOR_BLUE

        fields = [
            {"name": "Issue", "value": issue_link, "inline": True},
            {"name": "New Assignee", "value": new_assignee_name or "Unassigned", "inline": True},
            {"name": "Previous Assignee", "value": old_assignee_name or "None", "inline": True},
            {"name": "Title", "value": task_title or "Untitled", "inline": False},
        ]
        if assigned_by:
            fields.append({"name": "Assigned By", "value": assigned_by, "inline": True})

        return cls.format_embed(
            title=title,
            description=desc,
            color=color,
            fields=fields,
            timestamp=timestamp,
            url=jira_url
        )

    @classmethod
    def format_jira_navigator_link(cls, ticket_keys: List[str], label: Optional[str] = None) -> str:
        """Construct a clickable markdown link to Jira Issue Navigator for a list of tickets."""
        if not ticket_keys:
            return label or "0"
        url = settings.get_jira_issue_navigator_url(ticket_keys)
        unique_keys = sorted(list({k.strip() for k in ticket_keys if k and k.strip()}))
        display_label = label if label is not None else str(len(unique_keys))
        return f"[{display_label}]({url})"

    @staticmethod
    def _get_visual_length(text: str) -> int:
        """Calculate visual character width in monospace font (emojis count as 2)."""
        length = 0
        for char in text:
            if ord(char) > 0x2000:
                length += 2
            else:
                length += 1
        return length

    @classmethod
    def _pad_visual(cls, text: str, width: int) -> str:
        """Pad string to visual monospace width with trailing spaces."""
        vlen = cls._get_visual_length(text)
        pad = max(0, width - vlen)
        return text + (" " * pad)

    @classmethod
    def format_daily_worklog_report(cls, report_data: Dict[str, Any]) -> Dict[str, Any]:
        """Format daily team worklog report into a rich Discord embed with clickable Jira links and single unified table."""
        team_name = report_data.get("team_name", "Team")
        report_date = report_data.get("report_date", "Today")
        formatted_date = report_data.get("formatted_date") or report_date
        tickets_worked_count = report_data.get("tickets_worked_count", 0)

        # Build clean monospace table for all eligible members in a single table
        member_entries = report_data.get("members", [])
        table_text = ""
        if member_entries:
            # Determine maximum visual column width for member names, preserving full names without truncation
            max_name_len = 0
            for m in member_entries:
                name = m.get("display_name") or "Unknown"
                time_secs = m.get("time_logged_seconds", 0)
                ticket_keys = m.get("tickets", [])
                has_worked = (time_secs > 0) or (len(ticket_keys) > 0)
                disp_name = name if has_worked else f"🔴 {name}"
                vlen = cls._get_visual_length(disp_name)
                if vlen > max_name_len:
                    max_name_len = vlen

            col_member_w = max(24, max_name_len)
            col_time_w = 11
            col_tickets_w = 7

            header_line = f"| {'Team Member':<{col_member_w}} | {'Time Logged':<{col_time_w}} | {'Tickets':<{col_tickets_w}} |"
            sep_line = f"| {'-' * col_member_w} | {'-' * col_time_w} | {'-' * col_tickets_w} |"

            table_lines = [f"`{header_line}`", f"`{sep_line}`"]
            for m in member_entries:
                name = m.get("display_name") or "Unknown"
                time_secs = m.get("time_logged_seconds", 0)
                ticket_keys = m.get("tickets", [])
                has_worked = (time_secs > 0) or (len(ticket_keys) > 0)

                disp_name = name if has_worked else f"🔴 {name}"
                np = cls._pad_visual(disp_name, col_member_w)
                time_str = m.get("time_logged_human") or "0m" if has_worked else "0m"
                tp = cls._pad_visual(time_str, col_time_w)

                if has_worked:
                    unique_tickets = sorted(list({k.strip() for k in ticket_keys if k and k.strip()}))
                    t_count = m.get("tickets_count") or len(unique_tickets)
                    pad_t = " " * max(0, col_tickets_w - len(str(t_count)))
                    if unique_tickets:
                        nav_url = settings.get_jira_issue_navigator_url(unique_tickets)
                        tickets_cell = f"[{t_count}]({nav_url})"
                    else:
                        tickets_cell = str(t_count)
                    # Inline code wrapping ensures Discord maintains fixed-width monospace alignment
                    # while preserving clickable Jira link outside the backtick markers
                    row = f"`| {np} | {tp} | `{tickets_cell}`{pad_t} |`"
                else:
                    pad_t = " " * max(0, col_tickets_w - 1)
                    row = f"`| {np} | {tp} | 0{pad_t} |`"

                table_lines.append(row)

            table_text = "\n".join(table_lines)

        description = (
            f"**Date:** {formatted_date}\n"
            f"**Tickets Worked:** {tickets_worked_count}\n\n"
            f"👥 Team Worklog\n\n"
            f"{table_text}"
        )

        return cls.format_embed(
            title=f"📊 {team_name} — Daily Worklog",
            description=description,
            color=COLOR_PURPLE,
            fields=[]
        )

    @classmethod
    def format_daily_worklog_embed(cls, report_data: Dict[str, Any]) -> Dict[str, Any]:
        """Format daily worklog report into a clean, mobile-friendly Discord embed payload."""
        from app.core.reports.worklog_report import format_seconds

        raw_team_name = report_data.get("team_name") or "Mursaleen Cluster"
        clean_team_name = str(raw_team_name).replace("📊", "").strip()
        title = f"📊 {clean_team_name} — Daily Worklog"

        report_date = str(report_data.get("report_date") or report_data.get("date") or "Today").strip()
        if len(report_date) >= 10 and report_date[4] == "-" and report_date[7] == "-":
            clean_date = report_date[:10]
        else:
            clean_date = report_date

        tickets_worked = report_data.get("tickets_worked_count")
        if tickets_worked is None:
            tickets_worked = len(report_data.get("tickets", []))

        total_worklogs = report_data.get("total_worklogs")
        if total_worklogs is None:
            total_worklogs = report_data.get("total_worklogs_count")
        if total_worklogs is None:
            tickets = report_data.get("tickets") or []
            total_worklogs = sum(t.get("worklogs_count", 0) for t in tickets)

        all_members = report_data.get("members", [])
        active_members = []
        zero_member_names = []

        for zm in report_data.get("zero_worklog_members", []):
            if isinstance(zm, dict):
                zname = zm.get("display_name") or zm.get("name")
            else:
                zname = str(zm)
            if zname and zname not in zero_member_names:
                zero_member_names.append(zname)

        for m in all_members:
            name = m.get("display_name") or "Unknown"
            time_secs = m.get("time_logged_seconds", 0)
            ticket_keys = m.get("tickets", [])
            t_count = m.get("tickets_count") or len(ticket_keys)
            has_worked = (time_secs > 0) or (t_count > 0)
            if has_worked:
                active_members.append(m)
            else:
                if name and name not in zero_member_names:
                    zero_member_names.append(name)

        active_count = report_data.get("members_logged_count")
        if active_count is None:
            active_count = len(active_members)

        total_members_count = report_data.get("reportable_members_count")
        if total_members_count is None:
            total_members_count = active_count + len(zero_member_names)

        desc_lines = [
            f"**Date:** {clean_date}",
            f"**Tickets Worked:** {tickets_worked}",
            f"**Total Worklogs:** {total_worklogs}",
            f"**Active Members:** {active_count} / {total_members_count}",
            "",
            "👥 **Team Worklog**",
            "",
        ]

        if active_members:
            for m in active_members:
                name = m.get("display_name") or "Unknown"
                time_secs = m.get("time_logged_seconds", 0)
                time_str = m.get("time_logged_human") or format_seconds(time_secs)
                ticket_keys = m.get("tickets", [])
                unique_tickets = sorted(list({k.strip() for k in ticket_keys if k and k.strip()}))
                t_count = m.get("tickets_count") or len(unique_tickets)
                ticket_label = f"{t_count} ticket" if t_count == 1 else f"{t_count} tickets"

                if unique_tickets:
                    nav_url = settings.get_jira_issue_navigator_url(unique_tickets)
                    ticket_part = f"[{ticket_label}]({nav_url})"
                else:
                    ticket_part = ticket_label

                desc_lines.append(f"{name} — {time_str} — {ticket_part}")
        else:
            desc_lines.append("No work logged for this date.")

        if zero_member_names:
            desc_lines.append("")
            desc_lines.append("⏸️ **No Logged Work**")
            desc_lines.append("")
            sorted_zero = sorted(list(set(zero_member_names)), key=lambda s: s.lower())
            desc_lines.append(", ".join(sorted_zero))

        description = "\n".join(desc_lines)

        return {
            "embeds": [{
                "title": title,
                "description": description,
                "color": 0x9B59B6,
                "footer": {
                    "text": "Generated by PM Operations Agent"
                }
            }]
        }

    @classmethod
    def format_overdue_digest(cls, report_data: Dict[str, Any]) -> Dict[str, Any]:
        """Format daily consolidated overdue task digest for Discord mobile embed."""
        raw_team_name = report_data.get("team_name") or "Mursaleen Cluster"
        clean_team_name = str(raw_team_name).replace("📋", "").strip()
        title_base = f"📋 {clean_team_name} — Overdue Tasks"
        footer_text = "Generated by PM Operations Agent"

        date_str = report_data.get("formatted_date") or report_data.get("date") or "Today"
        tickets = report_data.get("tickets", [])
        overdue_count = report_data.get("overdue_count", len(tickets))

        if not tickets or overdue_count == 0:
            return {
                "embeds": [{
                    "title": title_base,
                    "description": f"**Date:** {date_str}\n\n✅ No overdue tasks found.",
                    "color": COLOR_GREEN,
                    "footer": {"text": footer_text}
                }]
            }

        # Calculate affected members
        unique_assignees = {
            (t.get("assignee") or "").strip()
            for t in tickets
            if (t.get("assignee") or "").strip() and (t.get("assignee") or "").strip() not in ("—", "Unassigned")
        }
        affected_members_count = len(unique_assignees) if unique_assignees else 1

        base_lines = [
            f"**Date:** {date_str}",
            f"**Total Overdue:** {overdue_count}",
            f"**Affected Members:** {affected_members_count}",
        ]

        raw_ticket_lines: List[str] = []
        for t in tickets:
            tkey = t.get("key", "—")
            turl = t.get("url") or (settings.get_jira_browse_url(tkey) if tkey != "—" else None)
            link_str = f"[{tkey}]({turl})" if turl and tkey != "—" else tkey
            summary = (t.get("summary") or "No summary").strip()
            assignee = (t.get("assignee") or "—").strip()
            due_date = str(t.get("due_date") or "—").strip()
            raw_ticket_lines.append(f"• {link_str}: {summary} — **{assignee}** (Due: {due_date})")

        MAX_TOTAL_BUDGET = 5800
        MAX_EMBED_DESC_LEN = 3800
        MAX_EMBEDS = 10

        item_header = ["", "⚠️ **Overdue Items**", ""]
        included_tickets: List[str] = []
        omitted_count = 0

        for tline in raw_ticket_lines:
            candidate_trans = included_tickets + [tline]
            remaining = len(raw_ticket_lines) - len(candidate_trans)
            candidate_lines = list(base_lines) + item_header + candidate_trans
            if remaining > 0:
                candidate_lines.append(f"• ... and {remaining} more overdue task(s)")

            res = cls._chunk_embed_lines(
                title_base=title_base,
                lines=candidate_lines,
                footer_text=footer_text,
                max_total_budget=MAX_TOTAL_BUDGET,
                max_embed_desc_len=MAX_EMBED_DESC_LEN,
                max_embeds=MAX_EMBEDS,
                color=COLOR_RED,
            )
            total_chars = sum(len(e["title"]) + len(e["description"]) + len(e.get("footer", {}).get("text", "")) for e in res["embeds"])

            if total_chars <= MAX_TOTAL_BUDGET and len(res["embeds"]) <= MAX_EMBEDS:
                included_tickets.append(tline)
            else:
                omitted_count = len(raw_ticket_lines) - len(included_tickets)
                break

        final_lines = list(base_lines)
        if included_tickets:
            final_lines.extend(item_header)
            final_lines.extend(included_tickets)
            if omitted_count > 0:
                final_lines.append(f"• ... and {omitted_count} more overdue task(s)")
        elif raw_ticket_lines and omitted_count > 0:
            final_lines.extend(item_header)
            final_lines.append(f"• ... and {omitted_count} more overdue task(s)")

        return cls._chunk_embed_lines(
            title_base=title_base,
            lines=final_lines,
            footer_text=footer_text,
            max_total_budget=MAX_TOTAL_BUDGET,
            max_embed_desc_len=MAX_EMBED_DESC_LEN,
            max_embeds=MAX_EMBEDS,
            color=COLOR_RED,
        )

    @classmethod
    def format_overdue_digest_embed(cls, report_data: Dict[str, Any]) -> Dict[str, Any]:
        """Alias for format_overdue_digest."""
        return cls.format_overdue_digest(report_data)

    @classmethod
    def format_overdue_digest_text(cls, report_data: Dict[str, Any]) -> str:
        """Format daily overdue tasks report into plain Discord markdown text with clickable Jira links."""
        raw_team_name = report_data.get("team_name") or "Mursaleen Cluster"
        clean_team_name = str(raw_team_name).replace("📋", "").strip()
        date_str = report_data.get("formatted_date") or report_data.get("date") or "Today"
        tickets = report_data.get("tickets", [])
        overdue_count = report_data.get("overdue_count", len(tickets))

        if not tickets or overdue_count == 0:
            return (
                f"📋 **{clean_team_name} — Overdue Tasks**\n"
                f"**Date:** {date_str}\n\n"
                f"✅ No overdue tasks found.\n\n"
                f"──────────────────────────────────────────────────\n"
                f"*Generated by PM Operations Agent*"
            )

        unique_assignees = {
            (t.get("assignee") or "").strip()
            for t in tickets
            if (t.get("assignee") or "").strip() and (t.get("assignee") or "").strip() not in ("—", "Unassigned")
        }
        affected_members_count = len(unique_assignees) if unique_assignees else 1

        lines = [
            f"📋 **{clean_team_name} — Overdue Tasks**",
            f"**Date:** {date_str}",
            f"**Total Overdue:** {overdue_count}",
            f"**Affected Members:** {affected_members_count}",
            "",
            "⚠️ **Overdue Items**:",
        ]

        for t in tickets[:40]:
            tkey = t.get("key", "—")
            turl = t.get("url") or (settings.get_jira_browse_url(tkey) if tkey != "—" else None)
            link_str = f"[{tkey}]({turl})" if turl and tkey != "—" else tkey
            summary = (t.get("summary") or "No summary").strip()
            assignee = (t.get("assignee") or "—").strip()
            due_date = str(t.get("due_date") or "—").strip()
            lines.append(f"• {link_str}: {summary} — **{assignee}** (Due: {due_date})")

        if len(tickets) > 40:
            lines.append(f"• ... and {len(tickets) - 40} more overdue task(s)")

        lines.append("")
        lines.append("──────────────────────────────────────────────────")
        lines.append("*Generated by PM Operations Agent*")

        return "\n".join(lines)

    @classmethod
    def format_daily_worklog_text(cls, report_data: Dict[str, Any]) -> str:
        """Format daily worklog report into plain Discord markdown text for slash commands."""
        team_name = report_data.get("team_name", "Team")
        report_date = report_data.get("report_date") or report_data.get("date") or "Today"
        tickets_worked_count = report_data.get("tickets_worked_count", 0)
        member_entries = report_data.get("members", [])

        table_text = ""
        if member_entries:
            max_name_len = 0
            for m in member_entries:
                name = m.get("display_name") or "Unknown"
                time_secs = m.get("time_logged_seconds", 0)
                ticket_keys = m.get("tickets", [])
                has_worked = (time_secs > 0) or (len(ticket_keys) > 0)
                disp_name = name if has_worked else f"🔴 {name}"
                vlen = cls._get_visual_length(disp_name)
                if vlen > max_name_len:
                    max_name_len = vlen

            col_member_w = max(24, max_name_len)
            col_time_w = 11
            col_tickets_w = 7

            header_line = f"| {'Team Member':<{col_member_w}} | {'Time Logged':<{col_time_w}} | {'Tickets':<{col_tickets_w}} |"
            sep_line = f"| {'-' * col_member_w} | {'-' * col_time_w} | {'-' * col_tickets_w} |"

            table_lines = [f"`{header_line}`", f"`{sep_line}`"]
            for m in member_entries:
                name = m.get("display_name") or "Unknown"
                time_secs = m.get("time_logged_seconds", 0)
                ticket_keys = m.get("tickets", [])
                has_worked = (time_secs > 0) or (len(ticket_keys) > 0)

                disp_name = name if has_worked else f"🔴 {name}"
                np = cls._pad_visual(disp_name, col_member_w)
                time_str = m.get("time_logged_human") or "0m" if has_worked else "0m"
                tp = cls._pad_visual(time_str, col_time_w)

                if has_worked:
                    unique_tickets = sorted(list({k.strip() for k in ticket_keys if k and k.strip()}))
                    t_count = m.get("tickets_count") or len(unique_tickets)
                    pad_t = " " * max(0, col_tickets_w - len(str(t_count)))
                    if unique_tickets:
                        nav_url = settings.get_jira_issue_navigator_url(unique_tickets)
                        tickets_cell = f"[{t_count}]({nav_url})"
                    else:
                        tickets_cell = str(t_count)
                    row = f"`| {np} | {tp} | `{tickets_cell}`{pad_t} |`"
                else:
                    pad_t = " " * max(0, col_tickets_w - 1)
                    row = f"`| {np} | {tp} | 0{pad_t} |`"

                table_lines.append(row)

            table_text = "\n".join(table_lines)

        return (
            f"📊 **{team_name} — Daily Worklog**\n"
            f"**Date:** {report_date}\n"
            f"**Tickets Worked:** {tickets_worked_count}\n\n"
            f"👥 **Team Worklog**\n\n"
            f"{table_text}\n\n"
            f"──────────────────────────────────────────────────\n"
            f"*Generated by PM Operations Agent*"
        )

    @classmethod
    def format_pm_attention_digest(cls, report_data: Dict[str, Any]) -> Dict[str, Any]:
        """Format daily consolidated PM Attention Digest into a mobile-first Discord embed payload."""
        raw_team_name = report_data.get("team_name") or "Mursaleen Cluster"
        clean_team_name = str(raw_team_name).replace("⚠️", "").replace("✅", "").strip()
        title_base = f"⚠️ {clean_team_name} — PM Attention Digest"
        footer_text = "Generated by PM Operations Agent"
        date_str = report_data.get("formatted_date") or report_data.get("date") or "Today"
        total_count = report_data.get("total_count", 0)
        categories = report_data.get("categories", {})

        if total_count == 0:
            return {
                "embeds": [{
                    "title": f"✅ {clean_team_name} — PM Attention Digest",
                    "description": f"**Date:** {date_str}\n\n✅ No items requiring attention.",
                    "color": COLOR_GREEN,
                    "footer": {"text": footer_text}
                }]
            }

        base_lines = [
            f"**Date:** {date_str}",
            f"**Total Items:** {total_count}",
        ]

        # Order categories strictly: inactive_stalled, reopened, unassigned
        category_order = [
            ("inactive_stalled", "🟠 Inactive / Stalled"),
            ("reopened", "🔁 Reopened"),
            ("unassigned", "📌 Unassigned"),
        ]

        candidate_sections: List[Dict[str, Any]] = []
        total_items_count = 0

        for cat_key, default_title in category_order:
            cat_info = categories.get(cat_key, {})
            cat_tickets = cat_info.get("tickets", [])
            if not cat_tickets:
                continue
            cat_title = cat_info.get("title") or default_title

            cat_lines: List[str] = []
            for t in cat_tickets:
                tkey = t.get("key", "Unknown")
                jira_url = t.get("url") or settings.get_jira_browse_url(tkey)
                status = t.get("status", "Unknown")
                upd_str = t.get("updated_at", "—")
                summary = t.get("summary")

                if cat_key == "inactive_stalled":
                    inactive_str = t.get("inactive_for", "—")
                    if summary:
                        item_line = f"• [{tkey}]({jira_url}): {summary} — **{status}** (Inactive: {inactive_str})"
                    else:
                        item_line = f"• [{tkey}]({jira_url}) — **{status}** (Inactive: {inactive_str}, Updated: {upd_str})"
                else:
                    if summary:
                        item_line = f"• [{tkey}]({jira_url}): {summary} — **{status}** (Updated: {upd_str})"
                    else:
                        item_line = f"• [{tkey}]({jira_url}) — **{status}** (Updated: {upd_str})"

                cat_lines.append(item_line)
                total_items_count += 1

            candidate_sections.append({
                "header": f"**{cat_title}**",
                "lines": cat_lines
            })

        MAX_TOTAL_BUDGET = 5800
        MAX_EMBED_DESC_LEN = 3800
        MAX_EMBEDS = 10

        # Build full candidate lines
        all_lines: List[str] = list(base_lines)
        for sec in candidate_sections:
            all_lines.append("")
            all_lines.append(sec["header"])
            all_lines.append("")
            all_lines.extend(sec["lines"])

        test_res = cls._chunk_embed_lines(
            title_base=title_base,
            lines=all_lines,
            footer_text=footer_text,
            max_total_budget=MAX_TOTAL_BUDGET,
            max_embed_desc_len=MAX_EMBED_DESC_LEN,
            max_embeds=MAX_EMBEDS,
            color=COLOR_AMBER,
        )
        total_chars = sum(len(e.get("title", "")) + len(e.get("description", "")) + len(e.get("footer", {}).get("text", "")) for e in test_res.get("embeds", []))

        if total_chars <= MAX_TOTAL_BUDGET and len(test_res.get("embeds", [])) <= MAX_EMBEDS:
            return test_res

        # Overflow handling if budget exceeded
        final_lines: List[str] = list(base_lines)
        included_count = 0
        omitted_count = 0

        for sec in candidate_sections:
            sec_header_added = False
            for line in sec["lines"]:
                candidate_lines = list(final_lines)
                if not sec_header_added:
                    candidate_lines.extend(["", sec["header"], ""])
                candidate_lines.append(line)
                remaining = total_items_count - (included_count + 1)
                if remaining > 0:
                    candidate_lines.append(f"• ... and {remaining} more attention item(s)")

                check_res = cls._chunk_embed_lines(
                    title_base=title_base,
                    lines=candidate_lines,
                    footer_text=footer_text,
                    max_total_budget=MAX_TOTAL_BUDGET,
                    max_embed_desc_len=MAX_EMBED_DESC_LEN,
                    max_embeds=MAX_EMBEDS,
                    color=COLOR_AMBER,
                )
                check_chars = sum(len(e.get("title", "")) + len(e.get("description", "")) + len(e.get("footer", {}).get("text", "")) for e in check_res.get("embeds", []))

                if check_chars <= MAX_TOTAL_BUDGET and len(check_res.get("embeds", [])) <= MAX_EMBEDS:
                    if not sec_header_added:
                        final_lines.extend(["", sec["header"], ""])
                        sec_header_added = True
                    final_lines.append(line)
                    included_count += 1
                else:
                    omitted_count = total_items_count - included_count
                    break
            if omitted_count > 0:
                break

        if omitted_count > 0:
            final_lines.append(f"• ... and {omitted_count} more attention item(s)")

        return cls._chunk_embed_lines(
            title_base=title_base,
            lines=final_lines,
            footer_text=footer_text,
            max_total_budget=MAX_TOTAL_BUDGET,
            max_embed_desc_len=MAX_EMBED_DESC_LEN,
            max_embeds=MAX_EMBEDS,
            color=COLOR_AMBER,
        )

    @classmethod
    def format_pm_attention_embed(cls, report_data: Dict[str, Any]) -> Dict[str, Any]:
        """Alias for format_pm_attention_digest."""
        return cls.format_pm_attention_digest(report_data)

    @classmethod
    def format_pm_attention_text(cls, report_data: Dict[str, Any]) -> str:
        """Format PM attention digest into plain Discord markdown text for slash commands."""
        team_name = report_data.get("team_name") or "Team"
        date_str = report_data.get("date") or report_data.get("formatted_date") or "Today"
        total_count = report_data.get("total_count", 0)
        categories = report_data.get("categories", {})

        if total_count == 0:
            return (
                f"✅ **{team_name} — PM Attention Digest**\n"
                f"**Date:** {date_str}\n\n"
                f"No items requiring attention.\n\n"
                f"──────────────────────────────────────────────────\n"
                f"*Generated by PM Operations Agent*"
            )

        sections = []
        # 1. Inactive / Stalled
        stale_info = categories.get("inactive_stalled", {})
        stale_tickets = stale_info.get("tickets", [])
        if stale_tickets:
            stale_title = stale_info.get("title", "🟠 Inactive / Stalled")
            col_ticket_w = max(11, max((len(t.get("key", "")) for t in stale_tickets), default=11))
            col_status_w = max(11, max((len(t.get("status", "")) for t in stale_tickets), default=11))
            col_updated_w = 12
            col_inactive_w = 12

            header_line = f"| {'Ticket':<{col_ticket_w}} | {'Status':<{col_status_w}} | {'Last Updated':<{col_updated_w}} | {'Inactive For':<{col_inactive_w}} |"
            sep_line = f"| {'-' * col_ticket_w} | {'-' * col_status_w} | {'-' * col_updated_w} | {'-' * col_inactive_w} |"

            table_lines = [f"`{header_line}`", f"`{sep_line}`"]
            for t in stale_tickets:
                tkey = t.get("key", "Unknown")
                jira_url = t.get("url") or settings.get_jira_browse_url(tkey)
                status_str = t.get("status", "Unknown")
                upd_str = t.get("updated_at", "—")
                inactive_str = t.get("inactive_for", "—")
                pad_ticket = " " * max(0, col_ticket_w - len(tkey))
                row = f"`| `[{tkey}]({jira_url})`{pad_ticket} | {status_str:<{col_status_w}} | {upd_str:<{col_updated_w}} | {inactive_str:<{col_inactive_w}} |`"
                table_lines.append(row)

            sections.append(f"**{stale_title}**\n\n" + "\n".join(table_lines))

        # 2. Reopened
        reopened_info = categories.get("reopened", {})
        reopened_tickets = reopened_info.get("tickets", [])
        if reopened_tickets:
            reopened_title = reopened_info.get("title", "🔁 Reopened")
            col_ticket_w = max(11, max((len(t.get("key", "")) for t in reopened_tickets), default=11))
            col_status_w = max(11, max((len(t.get("status", "")) for t in reopened_tickets), default=11))
            col_updated_w = 12

            header_line = f"| {'Ticket':<{col_ticket_w}} | {'Status':<{col_status_w}} | {'Last Updated':<{col_updated_w}} |"
            sep_line = f"| {'-' * col_ticket_w} | {'-' * col_status_w} | {'-' * col_updated_w} |"

            table_lines = [f"`{header_line}`", f"`{sep_line}`"]
            for t in reopened_tickets:
                tkey = t.get("key", "Unknown")
                jira_url = t.get("url") or settings.get_jira_browse_url(tkey)
                status_str = t.get("status", "Unknown")
                upd_str = t.get("updated_at", "—")
                pad_ticket = " " * max(0, col_ticket_w - len(tkey))
                row = f"`| `[{tkey}]({jira_url})`{pad_ticket} | {status_str:<{col_status_w}} | {upd_str:<{col_updated_w}} |`"
                table_lines.append(row)

            sections.append(f"**{reopened_title}**\n\n" + "\n".join(table_lines))

        # 3. Unassigned
        unassigned_info = categories.get("unassigned", {})
        unassigned_tickets = unassigned_info.get("tickets", [])
        if unassigned_tickets:
            unassigned_title = unassigned_info.get("title", "📌 Unassigned")
            col_ticket_w = max(11, max((len(t.get("key", "")) for t in unassigned_tickets), default=11))
            col_status_w = max(11, max((len(t.get("status", "")) for t in unassigned_tickets), default=11))
            col_updated_w = 12

            header_line = f"| {'Ticket':<{col_ticket_w}} | {'Status':<{col_status_w}} | {'Last Updated':<{col_updated_w}} |"
            sep_line = f"| {'-' * col_ticket_w} | {'-' * col_status_w} | {'-' * col_updated_w} |"

            table_lines = [f"`{header_line}`", f"`{sep_line}`"]
            for t in unassigned_tickets:
                tkey = t.get("key", "Unknown")
                jira_url = t.get("url") or settings.get_jira_browse_url(tkey)
                status_str = t.get("status", "Unknown")
                upd_str = t.get("updated_at", "—")
                pad_ticket = " " * max(0, col_ticket_w - len(tkey))
                row = f"`| `[{tkey}]({jira_url})`{pad_ticket} | {status_str:<{col_status_w}} | {upd_str:<{col_updated_w}} |`"
                table_lines.append(row)

            sections.append(f"**{unassigned_title}**\n\n" + "\n".join(table_lines))

        body = "\n\n".join(sections)
        return (
            f"⚠️ **{team_name} — PM Attention Digest**\n"
            f"**Date:** {date_str}\n\n"
            f"{body}\n\n"
            f"──────────────────────────────────────────────────\n"
            f"*Generated by PM Operations Agent*"
        )

    @classmethod
    def format_user_mapping_required(
        cls,
        jira_user_name: str,
        jira_user_id: str,
        intended_action: str,
        timestamp: Optional[str] = None
    ) -> Dict[str, Any]:
        """Format an alert when user mapping is missing for a direct message."""
        fields = [
            {"name": "Jira User", "value": f"{jira_user_name} (`{jira_user_id}`)", "inline": False},
            {"name": "Intended Action", "value": intended_action, "inline": False},
            {"name": "Status", "value": "❌ Direct Message was NOT sent.", "inline": False},
        ]
        return cls.format_embed(
            title="⚠️ Mattermost Mapping Required",
            description="No verified Mattermost account mapping exists for this resource. Please create a mapping in the database.",
            color=COLOR_AMBER,
            fields=fields,
            timestamp=timestamp
        )

    @classmethod
    def _chunk_embed_lines(
        cls,
        title_base: str,
        lines: List[str],
        footer_text: str = "Generated by PM Operations Agent",
        max_total_budget: int = 5800,
        max_embed_desc_len: int = 3800,
        max_embeds: int = 10,
        color: int = COLOR_PURPLE,
    ) -> Dict[str, Any]:
        """Chunk a sequence of lines across up to max_embeds, strictly enforcing cumulative and per-embed limits."""
        embeds: List[Dict[str, Any]] = []
        current_chunk_lines: List[str] = []
        current_chunk_len = 0
        cumulative_budget = 0
        part = 1
        footer_len = len(footer_text)

        for line in lines:
            line_len = len(line) + (1 if current_chunk_lines else 0)
            current_title = title_base if part == 1 else f"{title_base} (Part {part})"
            title_footer_overhead = len(current_title) + footer_len

            would_exceed_embed = (current_chunk_len + line_len > max_embed_desc_len)
            would_exceed_budget = (cumulative_budget + current_chunk_len + line_len + title_footer_overhead > max_total_budget)

            if (would_exceed_embed or would_exceed_budget) and current_chunk_lines:
                desc = "\n".join(current_chunk_lines)
                embeds.append({
                    "title": current_title,
                    "description": desc,
                    "color": color,
                    "footer": {"text": footer_text}
                })
                cumulative_budget += len(current_title) + len(desc) + footer_len
                part += 1
                current_chunk_lines = [line]
                current_chunk_len = len(line)

                if len(embeds) >= max_embeds:
                    break
            else:
                current_chunk_lines.append(line)
                current_chunk_len += line_len

        if current_chunk_lines and len(embeds) < max_embeds:
            current_title = title_base if part == 1 else f"{title_base} (Part {part})"
            desc = "\n".join(current_chunk_lines)
            embeds.append({
                "title": current_title,
                "description": desc,
                "color": color,
                "footer": {"text": footer_text}
            })

        return {"embeds": embeds[:max_embeds]}

    @classmethod
    def format_daily_report_embed(cls, report_data: Dict[str, Any]) -> Dict[str, Any]:
        """Format daily activity report into a clean, mobile-first Discord embed payload with clickable Jira links."""
        raw_team_name = report_data.get("team_name") or "Mursaleen Cluster"
        clean_team_name = str(raw_team_name).replace("📋", "").strip()
        title_base = f"📋 {clean_team_name} — Daily Activity Report"
        footer_text = "Generated by PM Operations Agent"

        date_str = report_data.get("formatted_date") or report_data.get("date") or "Today"
        total_activities = report_data.get("total_activities", 0)
        active_members_count = report_data.get("active_members_count", len(report_data.get("activities_by_resource", {})))

        tasks_created = report_data.get("tasks_created", 0)
        tasks_completed = report_data.get("tasks_completed", 0)
        transitions_count = report_data.get("status_transitions", 0)
        comments = report_data.get("comments_added", 0)
        worklogs = report_data.get("worklogs_logged", 0)
        violations = report_data.get("workflow_violations", 0)
        stale_count = report_data.get("stale_tasks", 0)

        # 1. Base Summary Lines (Always fully included)
        base_lines = [
            f"**Date:** {date_str}",
            f"**Total Activities:** {total_activities}",
            f"**Active Members:** {active_members_count}",
            "",
            "👥 **Activities by Member**",
            "",
        ]

        by_resource = report_data.get("activities_by_resource", {})
        if by_resource:
            for name, count in sorted(by_resource.items(), key=lambda x: (-x[1], x[0])):
                base_lines.append(f"• **{name}**: {count} activities")
        else:
            base_lines.append("• No recorded Mursaleen Cluster activity for this date.")

        base_lines.append("")
        base_lines.append("📊 **Activity Breakdown**")
        base_lines.append("")
        base_lines.append(f"• ✨ Tasks Created: {tasks_created}")
        base_lines.append(f"• 🔄 Status Transitions: {transitions_count}")
        base_lines.append(f"• 💬 Comments Added: {comments}")
        base_lines.append(f"• ⏱️ Worklogs Logged: {worklogs}")
        if violations > 0:
            base_lines.append(f"• 🚨 Workflow Violations: {violations}")
        if stale_count > 0:
            base_lines.append(f"• ⚠️ Stale Tasks: {stale_count}")

        # 2. Format Transition Lines
        transitions = report_data.get("recent_transitions", [])
        raw_transition_lines: List[str] = []
        if transitions:
            for t in transitions:
                tkey = t.get("task", "N/A")
                turl = t.get("task_url") or (settings.get_jira_browse_url(tkey) if tkey != "N/A" else None)
                if turl and tkey != "N/A":
                    link_str = f"[{tkey}]({turl})"
                else:
                    link_str = tkey
                old_st = t.get("old_status", "—")
                new_st = t.get("new_status", "—")
                actor = t.get("actor", "Team")
                raw_transition_lines.append(f"• {link_str}: `{old_st}` → `{new_st}` — {actor}")

        # 3. Budget Management (Discord cumulative embed limit is 6,000; budget is 5,800)
        MAX_TOTAL_BUDGET = 5800
        MAX_EMBED_DESC_LEN = 3800
        MAX_EMBEDS = 10

        if not raw_transition_lines:
            return cls._chunk_embed_lines(
                title_base=title_base,
                lines=base_lines,
                footer_text=footer_text,
                max_total_budget=MAX_TOTAL_BUDGET,
                max_embed_desc_len=MAX_EMBED_DESC_LEN,
                max_embeds=MAX_EMBEDS,
                color=COLOR_PURPLE,
            )

        transition_header = ["", "🔄 **Recent Transitions**", ""]
        included_transitions: List[str] = []
        omitted_count = 0

        for tline in raw_transition_lines:
            candidate_trans = included_transitions + [tline]
            remaining = len(raw_transition_lines) - len(candidate_trans)
            candidate_lines = list(base_lines) + transition_header + candidate_trans
            if remaining > 0:
                candidate_lines.append(f"• ... and {remaining} more transition(s)")

            res = cls._chunk_embed_lines(
                title_base=title_base,
                lines=candidate_lines,
                footer_text=footer_text,
                max_total_budget=MAX_TOTAL_BUDGET,
                max_embed_desc_len=MAX_EMBED_DESC_LEN,
                max_embeds=MAX_EMBEDS,
                color=COLOR_PURPLE,
            )
            total_chars = sum(len(e["title"]) + len(e["description"]) + len(e.get("footer", {}).get("text", "")) for e in res["embeds"])

            if total_chars <= MAX_TOTAL_BUDGET and len(res["embeds"]) <= MAX_EMBEDS:
                included_transitions.append(tline)
            else:
                omitted_count = len(raw_transition_lines) - len(included_transitions)
                break

        final_lines = list(base_lines)
        if included_transitions:
            final_lines.extend(transition_header)
            final_lines.extend(included_transitions)
            if omitted_count > 0:
                final_lines.append(f"• ... and {omitted_count} more transition(s)")
        elif raw_transition_lines and omitted_count > 0:
            final_lines.extend(transition_header)
            final_lines.append(f"• ... and {omitted_count} more transition(s)")

        return cls._chunk_embed_lines(
            title_base=title_base,
            lines=final_lines,
            footer_text=footer_text,
            max_total_budget=MAX_TOTAL_BUDGET,
            max_embed_desc_len=MAX_EMBED_DESC_LEN,
            max_embeds=MAX_EMBEDS,
            color=COLOR_PURPLE,
        )

    @classmethod
    def format_daily_report(cls, report_data: Dict[str, Any]) -> Dict[str, Any]:
        """Alias for format_daily_report_embed."""
        return cls.format_daily_report_embed(report_data)

    @classmethod
    def format_daily_report_text(cls, report_data: Dict[str, Any]) -> str:
        """Format daily activity report into plain Discord markdown text with clickable Jira links."""
        raw_team_name = report_data.get("team_name") or "Mursaleen Cluster"
        clean_team_name = str(raw_team_name).replace("📋", "").strip()
        date_str = report_data.get("formatted_date") or report_data.get("date") or "Today"
        total_activities = report_data.get("total_activities", 0)
        active_members = report_data.get("active_members_count", len(report_data.get("activities_by_resource", {})))

        lines = [
            f"📋 **{clean_team_name} — Daily Activity Report**",
            f"**Date:** {date_str}",
            f"**Total Activities:** {total_activities}",
            f"**Active Members:** {active_members}",
            "",
            "👥 **Activities by Member**:",
        ]

        by_resource = report_data.get("activities_by_resource", {})
        if by_resource:
            for name, count in sorted(by_resource.items(), key=lambda x: (-x[1], x[0])):
                lines.append(f"• **{name}**: {count} activities")
        else:
            lines.append("• No recorded Mursaleen Cluster activity for this date.")

        transitions = report_data.get("recent_transitions", [])
        if transitions:
            lines.append("")
            lines.append("🔄 **Recent Transitions**:")
            for t in transitions[:15]:
                tkey = t.get("task", "N/A")
                turl = t.get("task_url") or (settings.get_jira_browse_url(tkey) if tkey != "N/A" else None)
                if turl and tkey != "N/A":
                    link_str = f"[{tkey}]({turl})"
                else:
                    link_str = tkey
                old_st = t.get("old_status", "—")
                new_st = t.get("new_status", "—")
                actor = t.get("actor", "Team")
                lines.append(f"• {link_str}: `{old_st}` → `{new_st}` ({actor})")

            if len(transitions) > 15:
                lines.append(f"• ... and {len(transitions) - 15} more transition(s)")

        lines.append("")
        lines.append("📊 **Summary**:")
        lines.append(f"• ✨ Tasks Created: {report_data.get('tasks_created', 0)}")
        lines.append(f"• 🔄 Status Transitions: {report_data.get('status_transitions', 0)}")
        lines.append(f"• 💬 Comments Added: {report_data.get('comments_added', 0)}")
        lines.append(f"• ⏱️ Worklogs Logged: {report_data.get('worklogs_logged', 0)}")
        if report_data.get('workflow_violations', 0) > 0:
            lines.append(f"• 🚨 Workflow Violations: {report_data.get('workflow_violations', 0)}")
        if report_data.get('stale_tasks', 0) > 0:
            lines.append(f"• ⚠️ Stale Tasks: {report_data.get('stale_tasks', 0)}")

        lines.append("")
        lines.append("──────────────────────────────────────────────────")
        lines.append("*Generated by PM Operations Agent*")

        return "\n".join(lines)

    @classmethod
    def format_user_worklog_text(cls, report_data: Dict[str, Any]) -> str:
        """Format individual-resource daily worklog into clean monospace Discord markdown table."""
        display_name = report_data.get("display_name", "Resource")
        date_str = report_data.get("date", "Today")
        total_time = report_data.get("total_time_human", "0m")
        tickets = report_data.get("tickets", [])

        header = f"📊 **Daily Worklog — {display_name}**\n**Date:** {date_str}\n\n"

        if not tickets:
            return (
                f"{header}"
                f"No worklogs logged for {display_name} on {date_str}.\n\n"
                f"**Total:** {total_time}\n\n"
                f"──────────────────────────────────────────────────\n"
                f"*Generated by PM Operations Agent*"
            )

        table_lines = [
            "`| Ticket      | Time Logged |`",
            "`|-------------|------------:|`",
        ]
        for t in tickets:
            tkey = t.get("key", "Unknown")
            time_h = t.get("time_logged_human", "0m")
            url = t.get("url") or settings.get_jira_browse_url(tkey)
            pad_key = " " * max(0, 11 - len(tkey))
            pad_time = " " * max(0, 11 - len(time_h))
            table_lines.append(f"`| `[{tkey}]({url})`{pad_key} | {pad_time}{time_h} |`")

        table_str = "\n".join(table_lines)
        return (
            f"{header}"
            f"{table_str}\n\n"
            f"**Total:** {total_time}\n\n"
            f"──────────────────────────────────────────────────\n"
            f"*Generated by PM Operations Agent*"
        )

    @classmethod
    def format_user_overdue_digest_embed(cls, digest_data: Dict[str, Any]) -> Dict[str, Any]:
        """Format individual-resource overdue digest into a clean mobile-first Discord embed."""
        display_name = digest_data.get("display_name", "Resource")
        title_base = f"📋 Overdue Tasks — {display_name}"
        footer_text = "Generated by PM Operations Agent"

        date_str = digest_data.get("formatted_date") or digest_data.get("date") or "Today"
        tickets = digest_data.get("tickets", [])
        overdue_count = digest_data.get("overdue_count", len(tickets))

        if not tickets or overdue_count == 0:
            return {
                "embeds": [{
                    "title": title_base,
                    "description": f"**Date:** {date_str}\n\n✅ No overdue tasks found for {display_name}.",
                    "color": COLOR_GREEN,
                    "footer": {"text": footer_text}
                }]
            }

        base_lines = [
            f"**Date:** {date_str}",
            f"**Total Overdue:** {overdue_count}",
        ]

        raw_ticket_lines: List[str] = []
        for t in tickets:
            tkey = t.get("key", "—")
            turl = t.get("url") or (settings.get_jira_browse_url(tkey) if tkey != "—" else None)
            link_str = f"[{tkey}]({turl})" if turl and tkey != "—" else tkey
            summary = (t.get("summary") or "No summary").strip()
            due_date = str(t.get("due_date") or "—").strip()
            raw_ticket_lines.append(f"• {link_str}: {summary} (Due: {due_date})")

        MAX_TOTAL_BUDGET = 5800
        MAX_EMBED_DESC_LEN = 3800
        MAX_EMBEDS = 10

        item_header = ["", "⚠️ **Overdue Items**", ""]
        included_tickets: List[str] = []
        omitted_count = 0

        for tline in raw_ticket_lines:
            candidate_trans = included_tickets + [tline]
            remaining = len(raw_ticket_lines) - len(candidate_trans)
            candidate_lines = list(base_lines) + item_header + candidate_trans
            if remaining > 0:
                candidate_lines.append(f"• ... and {remaining} more overdue task(s)")

            res = cls._chunk_embed_lines(
                title_base=title_base,
                lines=candidate_lines,
                footer_text=footer_text,
                max_total_budget=MAX_TOTAL_BUDGET,
                max_embed_desc_len=MAX_EMBED_DESC_LEN,
                max_embeds=MAX_EMBEDS,
                color=COLOR_RED,
            )
            total_chars = sum(len(e["title"]) + len(e["description"]) + len(e.get("footer", {}).get("text", "")) for e in res["embeds"])

            if total_chars <= MAX_TOTAL_BUDGET and len(res["embeds"]) <= MAX_EMBEDS:
                included_tickets.append(tline)
            else:
                omitted_count = len(raw_ticket_lines) - len(included_tickets)
                break

        final_lines = list(base_lines)
        if included_tickets:
            final_lines.extend(item_header)
            final_lines.extend(included_tickets)
            if omitted_count > 0:
                final_lines.append(f"• ... and {omitted_count} more overdue task(s)")
        elif raw_ticket_lines and omitted_count > 0:
            final_lines.extend(item_header)
            final_lines.append(f"• ... and {omitted_count} more overdue task(s)")

        return cls._chunk_embed_lines(
            title_base=title_base,
            lines=final_lines,
            footer_text=footer_text,
            max_total_budget=MAX_TOTAL_BUDGET,
            max_embed_desc_len=MAX_EMBED_DESC_LEN,
            max_embeds=MAX_EMBEDS,
            color=COLOR_RED,
        )

    @classmethod
    def format_user_overdue_digest(cls, digest_data: Dict[str, Any]) -> Dict[str, Any]:
        """Alias for format_user_overdue_digest_embed."""
        return cls.format_user_overdue_digest_embed(digest_data)

    @classmethod
    def format_user_overdue_digest_text(cls, digest_data: Dict[str, Any]) -> str:
        """Format individual-resource overdue digest into clean Discord markdown text with clickable Jira links."""
        display_name = digest_data.get("display_name", "Resource")
        date_str = digest_data.get("formatted_date") or digest_data.get("date") or "Today"
        tickets = digest_data.get("tickets", [])
        overdue_count = digest_data.get("overdue_count", len(tickets))

        if not tickets or overdue_count == 0:
            return (
                f"📋 **Overdue Tasks — {display_name}**\n"
                f"**Date:** {date_str}\n\n"
                f"✅ No overdue tasks found for {display_name}.\n\n"
                f"──────────────────────────────────────────────────\n"
                f"*Generated by PM Operations Agent*"
            )

        lines = [
            f"📋 **Overdue Tasks — {display_name}**",
            f"**Date:** {date_str}",
            f"**Total Overdue:** {overdue_count}",
            "",
            "⚠️ **Overdue Items**:",
        ]

        for t in tickets[:40]:
            tkey = t.get("key", "—")
            turl = t.get("url") or (settings.get_jira_browse_url(tkey) if tkey != "—" else None)
            link_str = f"[{tkey}]({turl})" if turl and tkey != "—" else tkey
            summary = (t.get("summary") or "No summary").strip()
            due_date = str(t.get("due_date") or "—").strip()
            lines.append(f"• {link_str}: {summary} (Due: {due_date})")

        if len(tickets) > 40:
            lines.append(f"• ... and {len(tickets) - 40} more overdue task(s)")

        lines.append("")
        lines.append("──────────────────────────────────────────────────")
        lines.append("*Generated by PM Operations Agent*")

        return "\n".join(lines)

    @classmethod
    def format_user_active_queue_embed(cls, queue_data: Dict[str, Any]) -> Dict[str, Any]:
        """Format individual-resource active queue into a clean mobile-first Discord embed."""
        display_name = queue_data.get("display_name", "Resource")
        title_base = f"📋 Active Queue — {display_name}"
        footer_text = "Generated by PM Operations Agent"

        date_str = queue_data.get("formatted_date") or queue_data.get("date") or "Today"
        tickets = queue_data.get("tickets", [])
        active_count = queue_data.get("active_count", len(tickets))
        source = queue_data.get("source", "jira_live")
        cache_fallback = queue_data.get("cache_fallback", False)
        is_excluded = queue_data.get("is_excluded", False)

        if is_excluded:
            source_line = "⛔ Excluded from PM reporting"
        elif source == "jira_live":
            source_line = "🟢 Live Jira queue"
        elif cache_fallback:
            source_line = "🟠 Cached queue — Jira unavailable"
        else:
            source_line = "📋 Canonical queue"

        if not tickets or active_count == 0 or is_excluded:
            if is_excluded:
                desc = f"{source_line}\n**Date:** {date_str}\n\n❌ This resource is excluded from PM queue reporting."
            else:
                desc = f"{source_line}\n**Date:** {date_str}\n\n✅ No active tasks in queue for {display_name}."
            return {
                "embeds": [{
                    "title": title_base,
                    "description": desc,
                    "color": COLOR_GREEN if not is_excluded else COLOR_AMBER,
                    "footer": {"text": footer_text}
                }]
            }

        base_lines = [
            source_line,
            f"**Date:** {date_str}",
            f"**Active Tasks:** {active_count}",
        ]

        raw_ticket_lines: List[str] = []
        for t in tickets:
            tkey = t.get("key", "—")
            turl = t.get("url") or (settings.get_jira_browse_url(tkey) if tkey != "—" else None)
            link_str = f"[{tkey}]({turl})" if turl and tkey != "—" else tkey
            summary = (t.get("summary") or "Untitled").strip()
            status = (t.get("status") or "To Do").strip()
            priority = (t.get("priority") or "Medium").strip()
            due_date = str(t.get("due_date") or "—").strip()
            raw_ticket_lines.append(f"• {link_str}: {summary}\n  {status} • {priority} • Due: {due_date}")

        MAX_TOTAL_BUDGET = 5800
        MAX_EMBED_DESC_LEN = 3800
        MAX_EMBEDS = 10

        item_header = ["", "📌 **Active Tasks**:", ""]
        included_tickets: List[str] = []
        omitted_count = 0

        for titem in raw_ticket_lines:
            candidate_trans = included_tickets + [titem]
            remaining = len(raw_ticket_lines) - len(candidate_trans)
            candidate_lines = list(base_lines) + item_header + candidate_trans
            if remaining > 0:
                candidate_lines.append(f"• ... and {remaining} more active task(s)")

            res = cls._chunk_embed_lines(
                title_base=title_base,
                lines=candidate_lines,
                footer_text=footer_text,
                max_total_budget=MAX_TOTAL_BUDGET,
                max_embed_desc_len=MAX_EMBED_DESC_LEN,
                max_embeds=MAX_EMBEDS,
                color=COLOR_BLUE,
            )
            total_chars = sum(len(e["title"]) + len(e["description"]) + len(e.get("footer", {}).get("text", "")) for e in res["embeds"])

            if total_chars <= MAX_TOTAL_BUDGET and len(res["embeds"]) <= MAX_EMBEDS:
                included_tickets.append(titem)
            else:
                omitted_count = len(raw_ticket_lines) - len(included_tickets)
                break

        final_lines = list(base_lines)
        if included_tickets:
            final_lines.extend(item_header)
            final_lines.extend(included_tickets)
            if omitted_count > 0:
                final_lines.append(f"• ... and {omitted_count} more active task(s)")
        elif raw_ticket_lines and omitted_count > 0:
            final_lines.extend(item_header)
            final_lines.append(f"• ... and {omitted_count} more active task(s)")

        return cls._chunk_embed_lines(
            title_base=title_base,
            lines=final_lines,
            footer_text=footer_text,
            max_total_budget=MAX_TOTAL_BUDGET,
            max_embed_desc_len=MAX_EMBED_DESC_LEN,
            max_embeds=MAX_EMBEDS,
            color=COLOR_BLUE,
        )

    @classmethod
    def format_user_active_queue_text(cls, queue_data: Dict[str, Any]) -> str:
        """Format individual-resource active queue into clean mobile-friendly Discord markdown text."""
        display_name = queue_data.get("display_name", "Resource")
        date_str = queue_data.get("formatted_date") or queue_data.get("date") or "Today"
        tickets = queue_data.get("tickets", [])
        active_count = queue_data.get("active_count", len(tickets))
        source = queue_data.get("source", "jira_live")
        cache_fallback = queue_data.get("cache_fallback", False)
        is_excluded = queue_data.get("is_excluded", False)

        if is_excluded:
            source_line = "⛔ Excluded from PM reporting"
        elif source == "jira_live":
            source_line = "🟢 Live Jira queue"
        elif cache_fallback:
            source_line = "🟠 Cached queue — Jira unavailable"
        else:
            source_line = "📋 Canonical queue"

        if not tickets or active_count == 0 or is_excluded:
            if is_excluded:
                msg = "❌ This resource is excluded from PM queue reporting."
            else:
                msg = f"✅ No active tasks in queue for {display_name}."
            return (
                f"📋 **Active Queue — {display_name}**\n"
                f"{source_line}\n"
                f"**Date:** {date_str}\n\n"
                f"{msg}\n\n"
                f"**Total Active:** 0\n\n"
                f"──────────────────────────────────────────────────\n"
                f"*Generated by PM Operations Agent*"
            )

        lines = [
            f"📋 **Active Queue — {display_name}**",
            f"{source_line}",
            f"**Date:** {date_str}",
            f"**Total Active:** {active_count}",
            "",
            "📌 **Active Tasks**:",
        ]

        for t in tickets[:40]:
            tkey = t.get("key", "—")
            turl = t.get("url") or (settings.get_jira_browse_url(tkey) if tkey != "—" else None)
            link_str = f"[{tkey}]({turl})" if turl and tkey != "—" else tkey
            summary = (t.get("summary") or "Untitled").strip()
            status = (t.get("status") or "To Do").strip()
            priority = (t.get("priority") or "Medium").strip()
            due_date = str(t.get("due_date") or "—").strip()
            lines.append(f"• {link_str}: {summary}\n  {status} • {priority} • Due: {due_date}")

        if len(tickets) > 40:
            lines.append(f"• ... and {len(tickets) - 40} more active task(s)")

        lines.append("")
        lines.append("──────────────────────────────────────────────────\n*Generated by PM Operations Agent*")

        return "\n".join(lines)

    @classmethod
    def format_ticket_creation_notification(
        cls,
        task_key: str,
        summary: str,
        creator_name: str,
        issue_type: str,
        project_key: str,
        created_at: Optional[str] = None,
        policy_classification: str = "REVIEW",
        policy_reason: str = "",
    ) -> Dict[str, Any]:
        """Format instant Jira ticket creation alert as a prominent Discord embed with dark pink/red accent."""
        from app.core.reports.overdue_report import format_jira_updated_at
        created_display = format_jira_updated_at(created_at) if created_at else "Just now"
        url = settings.get_jira_browse_url(task_key)

        is_expected = policy_classification.upper() == "EXPECTED"
        title = f"🚨 Ticket Created — Expected" if is_expected else "⚠️ Ticket Created — Review"

        fields = [
            {"name": "🎫 Ticket", "value": f"[{task_key}]({url})", "inline": True},
            {"name": "👤 Created by", "value": creator_name, "inline": True},
            {"name": "🏷️ Type", "value": issue_type, "inline": True},
            {"name": "📁 Project", "value": project_key, "inline": True},
            {"name": "🕒 Created", "value": created_display, "inline": True},
            {"name": "📝 Summary", "value": summary[:500] if summary else "Untitled", "inline": False},
            {"name": "🛡️ Policy", "value": f"**{policy_classification.upper()}** — {policy_reason}", "inline": False},
        ]

        return cls.format_embed(
            title=title,
            description=f"Ticket creation event detected on project **{project_key}**.",
            color=COLOR_DARK_PINK,
            fields=fields,
            footer_text="Generated by PM Operations Agent",
            url=url,
        )

    @staticmethod
    def _resolve_mubashir_jira_url(item: Dict[str, Any], issue_key: str) -> Optional[str]:
        """Resolve Jira URL preferring item-provided jira_url or falling back to settings.get_jira_browse_url."""
        url = item.get("jira_url")
        if (not url or "your-domain" in url) and issue_key and issue_key != "Unknown":
            computed = settings.get_jira_browse_url(issue_key)
            if not url or "your-domain" not in computed:
                url = computed
        return url

    @classmethod
    def format_mubashir_automation_report(cls, report_data: Dict[str, Any]) -> Dict[str, Any]:
        """Format Mubashir Automation Report into a clean, mobile-first Discord embed payload with clickable Jira links."""
        title_base = "🤖 Mubashir Automation Report"
        footer_text = "PM Operations Agent — Mubashir Automation"

        date_str = report_data.get("formatted_date") or report_data.get("date") or "Today"
        total_comments = report_data.get("total_comments")
        if total_comments is None:
            by_auto = report_data.get("by_automation", {})
            total_comments = sum(len(v) for v in by_auto.values()) if by_auto else len(report_data.get("comments", []))

        if total_comments == 0:
            return {
                "embeds": [{
                    "title": title_base,
                    "description": f"**Date:** {date_str}\n\n✅ No Mubashir automation comments were added.",
                    "color": COLOR_GREEN,
                    "footer": {"text": footer_text}
                }]
            }

        base_lines = [
            f"**Date:** {date_str}",
            f"**Total Comments Added:** {total_comments}",
        ]

        # Extract by_automation grouping, falling back to comments list if needed
        by_automation = report_data.get("by_automation")
        if not by_automation and "comments" in report_data:
            by_automation = {}
            for c in report_data.get("comments", []):
                src = c.get("automation_source") or "Unknown"
                by_automation.setdefault(src, []).append(c)
        by_automation = by_automation or {}

        known_sources = [
            ("MubashirStaleSupport", "🕒 **MUBASHIR_STALE_SUPPORT**", "Mubashir stale support reminder"),
            ("MubashirSupportRule", "⚙️ **MUBASHIR_SUPPORT_RULE**", "Mubashir support creation workflow comment"),
        ]

        candidate_sections: List[Dict[str, Any]] = []
        total_items_count = 0

        # 1. Known sources in deterministic order
        for src_key, default_header, default_note in known_sources:
            items = by_automation.get(src_key, [])
            if not items:
                continue

            sec_lines: List[str] = []
            for item in items:
                issue_key = item.get("issue_key") or item.get("key") or item.get("target_id") or "Unknown"
                url = cls._resolve_mubashir_jira_url(item, issue_key)
                link_str = f"[{issue_key}]({url})" if url and issue_key != "Unknown" else (issue_key or "N/A")
                note = item.get("description") or item.get("note") or default_note
                sec_lines.append(f"• {link_str} — {note}")
                total_items_count += 1

            candidate_sections.append({
                "header": default_header,
                "lines": sec_lines
            })

        # 2. Unexpected / custom sources in alphabetical order
        extra_keys = sorted([k for k in by_automation.keys() if k not in ("MubashirStaleSupport", "MubashirSupportRule")])
        for extra_key in extra_keys:
            items = by_automation[extra_key]
            if not items:
                continue

            clean_name = str(extra_key).replace("*", "").strip().upper()
            fallback_header = f"🤖 **{clean_name}**"
            sec_lines: List[str] = []
            for item in items:
                issue_key = item.get("issue_key") or item.get("key") or item.get("target_id") or "Unknown"
                url = cls._resolve_mubashir_jira_url(item, issue_key)
                link_str = f"[{issue_key}]({url})" if url and issue_key != "Unknown" else (issue_key or "N/A")
                note = item.get("description") or item.get("note") or item.get("summary") or "Automated comment"
                sec_lines.append(f"• {link_str} — {note}")
                total_items_count += 1

            candidate_sections.append({
                "header": fallback_header,
                "lines": sec_lines
            })

        MAX_TOTAL_BUDGET = 5800
        MAX_EMBED_DESC_LEN = 3800
        MAX_EMBEDS = 10

        # Build full candidate lines
        all_lines: List[str] = list(base_lines)
        for sec in candidate_sections:
            all_lines.append("")
            all_lines.append(sec["header"])
            all_lines.extend(sec["lines"])

        test_res = cls._chunk_embed_lines(
            title_base=title_base,
            lines=all_lines,
            footer_text=footer_text,
            max_total_budget=MAX_TOTAL_BUDGET,
            max_embed_desc_len=MAX_EMBED_DESC_LEN,
            max_embeds=MAX_EMBEDS,
            color=COLOR_PURPLE,
        )
        total_chars = sum(
            len(e.get("title", "")) + len(e.get("description", "")) + len(e.get("footer", {}).get("text", ""))
            for e in test_res.get("embeds", [])
        )

        last_desc = test_res.get("embeds", [])[-1].get("description", "") if test_res.get("embeds") else ""
        last_item_line = candidate_sections[-1]["lines"][-1] if (candidate_sections and candidate_sections[-1]["lines"]) else ""
        all_fit = (last_item_line in last_desc) if last_item_line else True

        if total_chars <= MAX_TOTAL_BUDGET and len(test_res.get("embeds", [])) <= MAX_EMBEDS and all_fit:
            return test_res

        # Overflow handling if budget or embed limit exceeded
        final_lines: List[str] = list(base_lines)
        included_count = 0
        omitted_count = 0

        for sec in candidate_sections:
            sec_header_added = False
            for line in sec["lines"]:
                candidate_lines = list(final_lines)
                if not sec_header_added:
                    candidate_lines.extend(["", sec["header"]])
                candidate_lines.append(line)
                remaining = total_items_count - (included_count + 1)
                omission_line = f"• ... and {remaining} more automation comment(s)"
                if remaining > 0:
                    candidate_lines.append(omission_line)

                check_res = cls._chunk_embed_lines(
                    title_base=title_base,
                    lines=candidate_lines,
                    footer_text=footer_text,
                    max_total_budget=MAX_TOTAL_BUDGET,
                    max_embed_desc_len=MAX_EMBED_DESC_LEN,
                    max_embeds=MAX_EMBEDS,
                    color=COLOR_PURPLE,
                )
                check_chars = sum(
                    len(e.get("title", "")) + len(e.get("description", "")) + len(e.get("footer", {}).get("text", ""))
                    for e in check_res.get("embeds", [])
                )
                check_last_desc = check_res.get("embeds", [])[-1].get("description", "") if check_res.get("embeds") else ""
                expected_last = omission_line if remaining > 0 else line
                made_it = (expected_last in check_last_desc)

                if check_chars <= MAX_TOTAL_BUDGET and len(check_res.get("embeds", [])) <= MAX_EMBEDS and made_it:
                    if not sec_header_added:
                        final_lines.extend(["", sec["header"]])
                        sec_header_added = True
                    final_lines.append(line)
                    included_count += 1
                else:
                    omitted_count = total_items_count - included_count
                    break
            if omitted_count > 0:
                break

        if omitted_count > 0:
            final_lines.append(f"• ... and {omitted_count} more automation comment(s)")

        return cls._chunk_embed_lines(
            title_base=title_base,
            lines=final_lines,
            footer_text=footer_text,
            max_total_budget=MAX_TOTAL_BUDGET,
            max_embed_desc_len=MAX_EMBED_DESC_LEN,
            max_embeds=MAX_EMBEDS,
            color=COLOR_PURPLE,
        )

    @classmethod
    def format_mubashir_automation_report_embed(cls, report_data: Dict[str, Any]) -> Dict[str, Any]:
        """Alias for format_mubashir_automation_report."""
        return cls.format_mubashir_automation_report(report_data)

    @classmethod
    def format_mubashir_automation_report_text(cls, report_data: Dict[str, Any]) -> str:
        """Format plain-text markdown summary of Mubashir Automation Report."""
        date_str = report_data.get("formatted_date") or report_data.get("date") or "Today"
        total_comments = report_data.get("total_comments")
        if total_comments is None:
            by_auto = report_data.get("by_automation", {})
            total_comments = sum(len(v) for v in by_auto.values()) if by_auto else len(report_data.get("comments", []))

        if total_comments == 0:
            return (
                f"🤖 **Mubashir Automation Report**\n"
                f"**Date:** {date_str}\n\n"
                f"✅ No Mubashir automation comments were added.\n\n"
                f"──────────────────────────────────────────────────\n"
                f"*PM Operations Agent — Mubashir Automation*"
            )

        lines = [
            "🤖 **Mubashir Automation Report**",
            f"**Date:** {date_str}",
            f"**Total Comments Added:** {total_comments}",
        ]

        by_automation = report_data.get("by_automation") or {}
        if not by_automation and "comments" in report_data:
            by_automation = {}
            for c in report_data.get("comments", []):
                src = c.get("automation_source") or "Unknown"
                by_automation.setdefault(src, []).append(c)

        known_sources = [
            ("MubashirStaleSupport", "🕒 **MUBASHIR_STALE_SUPPORT**", "Mubashir stale support reminder"),
            ("MubashirSupportRule", "⚙️ **MUBASHIR_SUPPORT_RULE**", "Mubashir support creation workflow comment"),
        ]

        item_count = 0
        MAX_TEXT_ITEMS = 40
        omitted = 0

        for src_key, default_header, default_note in known_sources:
            items = by_automation.get(src_key, [])
            if not items:
                continue
            lines.append("")
            lines.append(default_header)
            for item in items:
                if item_count >= MAX_TEXT_ITEMS:
                    omitted += 1
                    continue
                issue_key = item.get("issue_key") or item.get("key") or item.get("target_id") or "Unknown"
                url = cls._resolve_mubashir_jira_url(item, issue_key)
                link_str = f"[{issue_key}]({url})" if url and issue_key != "Unknown" else (issue_key or "N/A")
                note = item.get("description") or item.get("note") or default_note
                lines.append(f"• {link_str} — {note}")
                item_count += 1

        extra_keys = sorted([k for k in by_automation.keys() if k not in ("MubashirStaleSupport", "MubashirSupportRule")])
        for extra_key in extra_keys:
            items = by_automation[extra_key]
            if not items:
                continue
            clean_name = str(extra_key).replace("*", "").strip().upper()
            lines.append("")
            lines.append(f"🤖 **{clean_name}**")
            for item in items:
                if item_count >= MAX_TEXT_ITEMS:
                    omitted += 1
                    continue
                issue_key = item.get("issue_key") or item.get("key") or item.get("target_id") or "Unknown"
                url = cls._resolve_mubashir_jira_url(item, issue_key)
                link_str = f"[{issue_key}]({url})" if url and issue_key != "Unknown" else (issue_key or "N/A")
                note = item.get("description") or item.get("note") or item.get("summary") or "Automated comment"
                lines.append(f"• {link_str} — {note}")
                item_count += 1

        if omitted > 0:
            lines.append(f"• ... and {omitted} more automation comment(s)")

        lines.append("")
        lines.append("──────────────────────────────────────────────────\n*PM Operations Agent — Mubashir Automation*")
        return "\n".join(lines)
