"""Discord rich embed message formatter."""

from typing import Any, Dict, List, Optional
from app.utils.time import utc_now_iso
from app.config.settings import settings


# Centralized Standardized Discord Color Constants (Decimal)
COLOR_ASSIGNMENT = 3066993      # #2ECC71 - Green (Assignment to me)
COLOR_NOTIFICATION = 3447003    # #3498DB - Blue (Mention / General notification)
COLOR_WORKLOG = 10181046        # #9B59B6 - Purple (Worklog / Reports)
COLOR_OVERDUE = 15158332        # #E74C3C - Red (Overdue, Blocked, Errors)
COLOR_ATTENTION = 15844367      # #F1C40F - Yellow (PM Attention, Stale, Warnings)
COLOR_TICKET_CREATED = 14689374 # #E0245E - Dark Pink / Red (Ticket Creation Notifications)

# Backwards compatibility aliases
COLOR_GREEN = COLOR_ASSIGNMENT
COLOR_BLUE = COLOR_NOTIFICATION
COLOR_PURPLE = COLOR_WORKLOG
COLOR_RED = COLOR_OVERDUE
COLOR_AMBER = COLOR_ATTENTION
COLOR_MAGENTA = COLOR_ATTENTION
COLOR_DARK_PINK = COLOR_TICKET_CREATED



class DiscordFormatter:
    """Formats notifications and events into Discord Webhook embed payloads."""

    @staticmethod
    def format_jira_link(task_key: str, label: Optional[str] = None) -> str:
        """Construct a clickable markdown link for Jira issues."""
        url = settings.get_jira_browse_url(task_key)
        display_label = label or task_key
        return f"[{display_label}]({url})"

    @staticmethod
    def format_embed(
        title: str,
        description: str,
        color: int = COLOR_BLUE,
        fields: Optional[List[Dict[str, Any]]] = None,
        footer_text: str = "Generated by PM Operations Agent",
        timestamp: Optional[str] = None,
        url: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Construct a Discord Webhook payload with a rich embed."""
        embed: Dict[str, Any] = {
            "title": title,
            "description": description,
            "color": color,
            "footer": {"text": footer_text},
            "timestamp": timestamp or utc_now_iso()
        }
        if url:
            embed["url"] = url
        if fields:
            embed["fields"] = fields

        return {"embeds": [embed]}

    @classmethod
    def format_status_reply(cls, issue_data: Dict[str, Any]) -> str:
        """Format a concise plain-text/markdown status reply for /pm status."""
        key = issue_data.get("key", "")
        fields = issue_data.get("fields", {})
        summary = fields.get("summary", "Untitled")
        status_name = fields.get("status", {}).get("name", "Unknown") if isinstance(fields.get("status"), dict) else str(fields.get("status") or "Unknown")
        assignee_data = fields.get("assignee")
        if isinstance(assignee_data, dict):
            assignee_name = assignee_data.get("displayName", "Unassigned")
        else:
            assignee_name = str(assignee_data or "Unassigned")
        priority_data = fields.get("priority")
        if isinstance(priority_data, dict):
            priority_name = priority_data.get("name", "None")
        else:
            priority_name = str(priority_data or "None")
        due_date = fields.get("duedate") or fields.get("due_date") or "None"

        return (
            f"📋 **{key}**: {summary}\n"
            f"• **Status:** {status_name}\n"
            f"• **Assignee:** {assignee_name}\n"
            f"• **Priority:** {priority_name}\n"
            f"• **Due:** {due_date}"
        )

    @classmethod
    def format_workflow_violation(
        cls,
        task_key: str,
        task_title: str,
        resource_name: str,
        project_name: str,
        details: str,
        timestamp: Optional[str] = None
    ) -> Dict[str, Any]:
        """Format a PM workflow violation alert."""
        issue_link = cls.format_jira_link(task_key)
        jira_url = settings.get_jira_browse_url(task_key)
        fields = [
            {"name": "Issue", "value": issue_link, "inline": True},
            {"name": "Project", "value": project_name or "N/A", "inline": True},
            {"name": "Resource", "value": resource_name or "Unassigned", "inline": True},
            {"name": "Title", "value": task_title or "Untitled", "inline": False},
            {"name": "Issue Details", "value": details, "inline": False},
        ]
        return cls.format_embed(
            title=f"🚨 Jira Workflow Alert — {task_key}",
            description=f"Activity detected on {issue_link} while remaining in **To Do**.",
            color=COLOR_RED,
            fields=fields,
            timestamp=timestamp,
            url=jira_url
        )

    @classmethod
    def format_stale_task(
        cls,
        task_key: str,
        task_title: str,
        assignee_name: str,
        hours_inactive: float,
        timestamp: Optional[str] = None
    ) -> Dict[str, Any]:
        """Format a stale task warning."""
        issue_link = cls.format_jira_link(task_key)
        jira_url = settings.get_jira_browse_url(task_key)
        fields = [
            {"name": "Issue", "value": issue_link, "inline": True},
            {"name": "Assigned to", "value": assignee_name or "Unassigned", "inline": True},
            {"name": "Inactivity", "value": f"{hours_inactive:.1f} hours", "inline": True},
            {"name": "Title", "value": task_title or "Untitled", "inline": False},
        ]
        return cls.format_embed(
            title=f"⚠️ Stale Task Alert — {task_key}",
            description=f"Task {issue_link} has been In Progress for >{int(hours_inactive)}h without activity.",
            color=COLOR_AMBER,
            fields=fields,
            timestamp=timestamp,
            url=jira_url
        )

    @classmethod
    def format_overdue_task(
        cls,
        task_key: str,
        task_title: str,
        assignee_name: str,
        due_date: str,
        current_status: str,
        timestamp: Optional[str] = None
    ) -> Dict[str, Any]:
        """Format an overdue task alert."""
        issue_link = cls.format_jira_link(task_key)
        jira_url = settings.get_jira_browse_url(task_key)
        fields = [
            {"name": "Issue", "value": issue_link, "inline": True},
            {"name": "Assignee", "value": assignee_name or "Unassigned", "inline": True},
            {"name": "Status", "value": current_status, "inline": True},
            {"name": "Due Date", "value": due_date, "inline": True},
            {"name": "Title", "value": task_title or "Untitled", "inline": False},
        ]
        return cls.format_embed(
            title=f"⏰ Overdue Task Alert — {task_key}",
            description=f"Task {issue_link} passed its due date ({due_date}) and is not Done.",
            color=COLOR_OVERDUE,
            fields=fields,
            timestamp=timestamp,
            url=jira_url
        )

    @classmethod
    def format_reopened_task(
        cls,
        task_key: str,
        task_title: str,
        reopened_by: str,
        prev_status: str,
        new_status: str,
        timestamp: Optional[str] = None
    ) -> Dict[str, Any]:
        """Format a reopened task alert."""
        issue_link = cls.format_jira_link(task_key)
        jira_url = settings.get_jira_browse_url(task_key)
        fields = [
            {"name": "Issue", "value": issue_link, "inline": True},
            {"name": "Reopened by", "value": reopened_by or "Unknown", "inline": True},
            {"name": "Transition", "value": f"`{prev_status}` ➔ `{new_status}`", "inline": True},
            {"name": "Title", "value": task_title or "Untitled", "inline": False},
        ]
        return cls.format_embed(
            title=f"🔄 Task Reopened Alert — {task_key}",
            description=f"Task {issue_link} was reopened from **{prev_status}** to **{new_status}**.",
            color=COLOR_BLUE,
            fields=fields,
            timestamp=timestamp,
            url=jira_url
        )

    @classmethod
    def format_task_comment(
        cls,
        task_key: str,
        task_title: str,
        author_name: str,
        comment_body: str,
        task_status: str,
        timestamp: Optional[str] = None
    ) -> Dict[str, Any]:
        """Format a general comment notification alert."""
        issue_link = cls.format_jira_link(task_key)
        jira_url = settings.get_jira_browse_url(task_key)
        preview = comment_body if len(comment_body) <= 400 else comment_body[:397] + "..."
        fields = [
            {"name": "Issue", "value": issue_link, "inline": True},
            {"name": "Status", "value": task_status or "Unknown", "inline": True},
            {"name": "Author", "value": author_name or "Unknown", "inline": True},
            {"name": "Title", "value": task_title or "Untitled", "inline": False},
            {"name": "Comment", "value": preview or "(empty)", "inline": False},
        ]
        return cls.format_embed(
            title=f"💬 Jira Comment Added — {task_key}",
            description=f"New comment posted on {issue_link} by **{author_name or 'Unknown'}**.",
            color=COLOR_BLUE,
            fields=fields,
            timestamp=timestamp,
            url=jira_url
        )

    @classmethod
    def format_task_mention(
        cls,
        task_key: str,
        task_title: str,
        author_name: str,
        comment_body: str,
        task_status: str,
        timestamp: Optional[str] = None
    ) -> Dict[str, Any]:
        """Format a high-priority personal mention notification alert."""
        issue_link = cls.format_jira_link(task_key)
        jira_url = settings.get_jira_browse_url(task_key)
        preview = comment_body if len(comment_body) <= 500 else comment_body[:497] + "..."
        fields = [
            {"name": "Issue", "value": issue_link, "inline": True},
            {"name": "Status", "value": task_status or "Unknown", "inline": True},
            {"name": "Mentioned by", "value": author_name or "Unknown", "inline": True},
            {"name": "Title", "value": task_title or "Untitled", "inline": False},
            {"name": "Comment", "value": preview or "(empty)", "inline": False},
        ]
        return cls.format_embed(
            title=f"🔔 You were mentioned on {task_key}",
            description=f"**{author_name or 'Someone'}** mentioned you in a comment on {issue_link}.",
            color=COLOR_AMBER,
            fields=fields,
            timestamp=timestamp,
            url=jira_url
        )

    @classmethod
    def format_task_assigned(
        cls,
        task_key: str,
        task_title: str,
        new_assignee_name: str,
        old_assignee_name: Optional[str] = None,
        assigned_by: Optional[str] = None,
        is_assigned_to_me: bool = False,
        timestamp: Optional[str] = None
    ) -> Dict[str, Any]:
        """Format a ticket assignment notification."""
        issue_link = cls.format_jira_link(task_key)
        jira_url = settings.get_jira_browse_url(task_key)
        
        if is_assigned_to_me:
            title = f"🎯 Task Assigned to You — {task_key}"
            desc = f"You have been assigned to task {issue_link}."
            color = COLOR_GREEN
        else:
            title = f"👤 Task Assigned — {task_key}"
            desc = f"Task {issue_link} was assigned to **{new_assignee_name or 'Unassigned'}**."
            color = COLOR_BLUE

        fields = [
            {"name": "Issue", "value": issue_link, "inline": True},
            {"name": "New Assignee", "value": new_assignee_name or "Unassigned", "inline": True},
            {"name": "Previous Assignee", "value": old_assignee_name or "None", "inline": True},
            {"name": "Title", "value": task_title or "Untitled", "inline": False},
        ]
        if assigned_by:
            fields.append({"name": "Assigned By", "value": assigned_by, "inline": True})

        return cls.format_embed(
            title=title,
            description=desc,
            color=color,
            fields=fields,
            timestamp=timestamp,
            url=jira_url
        )

    @classmethod
    def format_jira_navigator_link(cls, ticket_keys: List[str], label: Optional[str] = None) -> str:
        """Construct a clickable markdown link to Jira Issue Navigator for a list of tickets."""
        if not ticket_keys:
            return label or "0"
        url = settings.get_jira_issue_navigator_url(ticket_keys)
        unique_keys = sorted(list({k.strip() for k in ticket_keys if k and k.strip()}))
        display_label = label if label is not None else str(len(unique_keys))
        return f"[{display_label}]({url})"

    @staticmethod
    def _get_visual_length(text: str) -> int:
        """Calculate visual character width in monospace font (emojis count as 2)."""
        length = 0
        for char in text:
            if ord(char) > 0x2000:
                length += 2
            else:
                length += 1
        return length

    @classmethod
    def _pad_visual(cls, text: str, width: int) -> str:
        """Pad string to visual monospace width with trailing spaces."""
        vlen = cls._get_visual_length(text)
        pad = max(0, width - vlen)
        return text + (" " * pad)

    @classmethod
    def format_daily_worklog_report(cls, report_data: Dict[str, Any]) -> Dict[str, Any]:
        """Format daily team worklog report into a rich Discord embed with clickable Jira links and single unified table."""
        team_name = report_data.get("team_name", "Team")
        report_date = report_data.get("report_date", "Today")
        formatted_date = report_data.get("formatted_date") or report_date
        tickets_worked_count = report_data.get("tickets_worked_count", 0)

        # Build clean monospace table for all eligible members in a single table
        member_entries = report_data.get("members", [])
        table_text = ""
        if member_entries:
            # Determine maximum visual column width for member names, preserving full names without truncation
            max_name_len = 0
            for m in member_entries:
                name = m.get("display_name") or "Unknown"
                time_secs = m.get("time_logged_seconds", 0)
                ticket_keys = m.get("tickets", [])
                has_worked = (time_secs > 0) or (len(ticket_keys) > 0)
                disp_name = name if has_worked else f"🔴 {name}"
                vlen = cls._get_visual_length(disp_name)
                if vlen > max_name_len:
                    max_name_len = vlen

            col_member_w = max(24, max_name_len)
            col_time_w = 11
            col_tickets_w = 7

            header_line = f"| {'Team Member':<{col_member_w}} | {'Time Logged':<{col_time_w}} | {'Tickets':<{col_tickets_w}} |"
            sep_line = f"| {'-' * col_member_w} | {'-' * col_time_w} | {'-' * col_tickets_w} |"

            table_lines = [f"`{header_line}`", f"`{sep_line}`"]
            for m in member_entries:
                name = m.get("display_name") or "Unknown"
                time_secs = m.get("time_logged_seconds", 0)
                ticket_keys = m.get("tickets", [])
                has_worked = (time_secs > 0) or (len(ticket_keys) > 0)

                disp_name = name if has_worked else f"🔴 {name}"
                np = cls._pad_visual(disp_name, col_member_w)
                time_str = m.get("time_logged_human") or "0m" if has_worked else "0m"
                tp = cls._pad_visual(time_str, col_time_w)

                if has_worked:
                    unique_tickets = sorted(list({k.strip() for k in ticket_keys if k and k.strip()}))
                    t_count = m.get("tickets_count") or len(unique_tickets)
                    pad_t = " " * max(0, col_tickets_w - len(str(t_count)))
                    if unique_tickets:
                        nav_url = settings.get_jira_issue_navigator_url(unique_tickets)
                        tickets_cell = f"[{t_count}]({nav_url})"
                    else:
                        tickets_cell = str(t_count)
                    # Inline code wrapping ensures Discord maintains fixed-width monospace alignment
                    # while preserving clickable Jira link outside the backtick markers
                    row = f"`| {np} | {tp} | `{tickets_cell}`{pad_t} |`"
                else:
                    pad_t = " " * max(0, col_tickets_w - 1)
                    row = f"`| {np} | {tp} | 0{pad_t} |`"

                table_lines.append(row)

            table_text = "\n".join(table_lines)

        description = (
            f"**Date:** {formatted_date}\n"
            f"**Tickets Worked:** {tickets_worked_count}\n\n"
            f"👥 Team Worklog\n\n"
            f"{table_text}"
        )

        return cls.format_embed(
            title=f"📊 {team_name} — Daily Worklog",
            description=description,
            color=COLOR_PURPLE,
            fields=[]
        )

    @classmethod
    def format_daily_worklog_embed(cls, report_data: Dict[str, Any]) -> Dict[str, Any]:
        """Format daily worklog report into a clean, mobile-friendly Discord embed payload."""
        from app.core.reports.worklog_report import format_seconds

        raw_team_name = report_data.get("team_name") or "Mursaleen Cluster"
        clean_team_name = str(raw_team_name).replace("📊", "").strip()
        title = f"📊 {clean_team_name} — Daily Worklog"

        report_date = str(report_data.get("report_date") or report_data.get("date") or "Today").strip()
        if len(report_date) >= 10 and report_date[4] == "-" and report_date[7] == "-":
            clean_date = report_date[:10]
        else:
            clean_date = report_date

        tickets_worked = report_data.get("tickets_worked_count")
        if tickets_worked is None:
            tickets_worked = len(report_data.get("tickets", []))

        total_worklogs = report_data.get("total_worklogs")
        if total_worklogs is None:
            total_worklogs = report_data.get("total_worklogs_count")
        if total_worklogs is None:
            tickets = report_data.get("tickets") or []
            total_worklogs = sum(t.get("worklogs_count", 0) for t in tickets)

        all_members = report_data.get("members", [])
        active_members = []
        zero_member_names = []

        for zm in report_data.get("zero_worklog_members", []):
            if isinstance(zm, dict):
                zname = zm.get("display_name") or zm.get("name")
            else:
                zname = str(zm)
            if zname and zname not in zero_member_names:
                zero_member_names.append(zname)

        for m in all_members:
            name = m.get("display_name") or "Unknown"
            time_secs = m.get("time_logged_seconds", 0)
            ticket_keys = m.get("tickets", [])
            t_count = m.get("tickets_count") or len(ticket_keys)
            has_worked = (time_secs > 0) or (t_count > 0)
            if has_worked:
                active_members.append(m)
            else:
                if name and name not in zero_member_names:
                    zero_member_names.append(name)

        active_count = report_data.get("members_logged_count")
        if active_count is None:
            active_count = len(active_members)

        total_members_count = report_data.get("reportable_members_count")
        if total_members_count is None:
            total_members_count = active_count + len(zero_member_names)

        desc_lines = [
            f"**Date:** {clean_date}",
            f"**Tickets Worked:** {tickets_worked}",
            f"**Total Worklogs:** {total_worklogs}",
            f"**Active Members:** {active_count} / {total_members_count}",
            "",
            "👥 **Team Worklog**",
            "",
        ]

        if active_members:
            for m in active_members:
                name = m.get("display_name") or "Unknown"
                time_secs = m.get("time_logged_seconds", 0)
                time_str = m.get("time_logged_human") or format_seconds(time_secs)
                ticket_keys = m.get("tickets", [])
                unique_tickets = sorted(list({k.strip() for k in ticket_keys if k and k.strip()}))
                t_count = m.get("tickets_count") or len(unique_tickets)
                ticket_label = f"{t_count} ticket" if t_count == 1 else f"{t_count} tickets"

                if unique_tickets:
                    nav_url = settings.get_jira_issue_navigator_url(unique_tickets)
                    ticket_part = f"[{ticket_label}]({nav_url})"
                else:
                    ticket_part = ticket_label

                desc_lines.append(f"{name} — {time_str} — {ticket_part}")
        else:
            desc_lines.append("No work logged for this date.")

        if zero_member_names:
            desc_lines.append("")
            desc_lines.append("⏸️ **No Logged Work**")
            desc_lines.append("")
            sorted_zero = sorted(list(set(zero_member_names)), key=lambda s: s.lower())
            desc_lines.append(", ".join(sorted_zero))

        description = "\n".join(desc_lines)

        return {
            "embeds": [{
                "title": title,
                "description": description,
                "color": 0x9B59B6,
                "footer": {
                    "text": "Generated by PM Operations Agent"
                }
            }]
        }

    @classmethod
    def format_overdue_digest(cls, report_data: Dict[str, Any]) -> Dict[str, Any]:
        """Format daily consolidated overdue task digest for Discord embed."""
        team_name = report_data.get("team_name")
        title_prefix = f"{team_name} — " if team_name else ""
        date_str = report_data.get("date") or report_data.get("formatted_date") or "Today"
        tickets = report_data.get("tickets", [])

        if not tickets:
            title = f"📋 {title_prefix}Overdue Tasks"
            description = f"**Date:** {date_str}\n\nNo overdue tasks found."
            return cls.format_embed(
                title=title,
                description=description,
                color=COLOR_GREEN,
                fields=[],
                footer_text="Generated by PM Operations Agent"
            )

        title = f"📋 {title_prefix}Overdue Tasks"

        # Calculate column widths
        col_ticket_w = max(10, max((len(t.get("key", "")) for t in tickets), default=10))
        col_ass_w = max(14, max((len(str(t.get("assignee") or "—")) for t in tickets), default=14))
        col_due_w = 12
        col_upd_w = 18

        header_line = f"| {'Ticket':<{col_ticket_w}} | {'Assignee':<{col_ass_w}} | {'Due Date':<{col_due_w}} | {'Last Updated':<{col_upd_w}} |"
        sep_line = f"| {'-' * col_ticket_w} | {'-' * col_ass_w} | {'-' * col_due_w} | {'-' * col_upd_w} |"

        table_lines = [f"`{header_line}`", f"`{sep_line}`"]
        for t in tickets:
            tkey = t.get("key", "—")
            turl = t.get("url") or settings.get_jira_browse_url(tkey)
            ass_str = str(t.get("assignee") or "—")
            due_str = str(t.get("due_date") or "—")
            upd_str = str(t.get("updated_at") or "—")

            pad_ticket = " " * max(0, col_ticket_w - len(tkey))
            pad_ass = " " * max(0, col_ass_w - len(ass_str))

            row = f"`| `[{tkey}]({turl})`{pad_ticket} | {ass_str}{pad_ass} | {due_str:<{col_due_w}} | {upd_str:<{col_upd_w}} |`"
            table_lines.append(row)

        table_block = "\n".join(table_lines)
        description = f"**Date:** {date_str}\n\n{table_block}"

        return cls.format_embed(
            title=title,
            description=description,
            color=COLOR_RED,
            fields=[],
            footer_text="Generated by PM Operations Agent"
        )

    @classmethod
    def format_overdue_digest_text(cls, report_data: Dict[str, Any]) -> str:
        """Format daily overdue tasks report into plain Discord markdown text for slash commands."""
        team_name = report_data.get("team_name")
        title_prefix = f"{team_name} — " if team_name else ""
        date_str = report_data.get("date") or report_data.get("formatted_date") or "Today"
        tickets = report_data.get("tickets", [])

        if not tickets:
            return (
                f"📋 **{title_prefix}Overdue Tasks**\n"
                f"**Date:** {date_str}\n\n"
                f"No overdue tasks found.\n\n"
                f"──────────────────────────────────────────────────\n"
                f"*Generated by PM Operations Agent*"
            )

        col_ticket_w = max(10, max((len(t.get("key", "")) for t in tickets), default=10))
        col_ass_w = max(14, max((len(str(t.get("assignee") or "—")) for t in tickets), default=14))
        col_due_w = 12
        col_upd_w = 18

        header_line = f"| {'Ticket':<{col_ticket_w}} | {'Assignee':<{col_ass_w}} | {'Due Date':<{col_due_w}} | {'Last Updated':<{col_upd_w}} |"
        sep_line = f"| {'-' * col_ticket_w} | {'-' * col_ass_w} | {'-' * col_due_w} | {'-' * col_upd_w} |"

        table_lines = [f"`{header_line}`", f"`{sep_line}`"]
        for t in tickets:
            tkey = t.get("key", "—")
            turl = t.get("url") or settings.get_jira_browse_url(tkey)
            ass_str = str(t.get("assignee") or "—")
            due_str = str(t.get("due_date") or "—")
            upd_str = str(t.get("updated_at") or "—")

            pad_ticket = " " * max(0, col_ticket_w - len(tkey))
            pad_ass = " " * max(0, col_ass_w - len(ass_str))

            row = f"`| `[{tkey}]({turl})`{pad_ticket} | {ass_str}{pad_ass} | {due_str:<{col_due_w}} | {upd_str:<{col_upd_w}} |`"
            table_lines.append(row)

        table_block = "\n".join(table_lines)
        return (
            f"📋 **{title_prefix}Overdue Tasks**\n"
            f"**Date:** {date_str}\n\n"
            f"{table_block}\n\n"
            f"──────────────────────────────────────────────────\n"
            f"*Generated by PM Operations Agent*"
        )

    @classmethod
    def format_daily_worklog_text(cls, report_data: Dict[str, Any]) -> str:
        """Format daily worklog report into plain Discord markdown text for slash commands."""
        team_name = report_data.get("team_name", "Team")
        report_date = report_data.get("report_date") or report_data.get("date") or "Today"
        tickets_worked_count = report_data.get("tickets_worked_count", 0)
        member_entries = report_data.get("members", [])

        table_text = ""
        if member_entries:
            max_name_len = 0
            for m in member_entries:
                name = m.get("display_name") or "Unknown"
                time_secs = m.get("time_logged_seconds", 0)
                ticket_keys = m.get("tickets", [])
                has_worked = (time_secs > 0) or (len(ticket_keys) > 0)
                disp_name = name if has_worked else f"🔴 {name}"
                vlen = cls._get_visual_length(disp_name)
                if vlen > max_name_len:
                    max_name_len = vlen

            col_member_w = max(24, max_name_len)
            col_time_w = 11
            col_tickets_w = 7

            header_line = f"| {'Team Member':<{col_member_w}} | {'Time Logged':<{col_time_w}} | {'Tickets':<{col_tickets_w}} |"
            sep_line = f"| {'-' * col_member_w} | {'-' * col_time_w} | {'-' * col_tickets_w} |"

            table_lines = [f"`{header_line}`", f"`{sep_line}`"]
            for m in member_entries:
                name = m.get("display_name") or "Unknown"
                time_secs = m.get("time_logged_seconds", 0)
                ticket_keys = m.get("tickets", [])
                has_worked = (time_secs > 0) or (len(ticket_keys) > 0)

                disp_name = name if has_worked else f"🔴 {name}"
                np = cls._pad_visual(disp_name, col_member_w)
                time_str = m.get("time_logged_human") or "0m" if has_worked else "0m"
                tp = cls._pad_visual(time_str, col_time_w)

                if has_worked:
                    unique_tickets = sorted(list({k.strip() for k in ticket_keys if k and k.strip()}))
                    t_count = m.get("tickets_count") or len(unique_tickets)
                    pad_t = " " * max(0, col_tickets_w - len(str(t_count)))
                    if unique_tickets:
                        nav_url = settings.get_jira_issue_navigator_url(unique_tickets)
                        tickets_cell = f"[{t_count}]({nav_url})"
                    else:
                        tickets_cell = str(t_count)
                    row = f"`| {np} | {tp} | `{tickets_cell}`{pad_t} |`"
                else:
                    pad_t = " " * max(0, col_tickets_w - 1)
                    row = f"`| {np} | {tp} | 0{pad_t} |`"

                table_lines.append(row)

            table_text = "\n".join(table_lines)

        return (
            f"📊 **{team_name} — Daily Worklog**\n"
            f"**Date:** {report_date}\n"
            f"**Tickets Worked:** {tickets_worked_count}\n\n"
            f"👥 **Team Worklog**\n\n"
            f"{table_text}\n\n"
            f"──────────────────────────────────────────────────\n"
            f"*Generated by PM Operations Agent*"
        )

    @classmethod
    def format_pm_attention_digest(cls, report_data: Dict[str, Any]) -> Dict[str, Any]:
        """Format daily consolidated PM Attention Digest for Discord embed."""
        team_name = report_data.get("team_name") or "Team"
        date_str = report_data.get("date") or report_data.get("formatted_date") or "Today"
        total_count = report_data.get("total_count", 0)
        categories = report_data.get("categories", {})

        if total_count == 0:
            title = f"✅ {team_name} — PM Attention Digest"
            description = f"**Date:** {date_str}\n\nNo items requiring attention."
            return cls.format_embed(
                title=title,
                description=description,
                color=COLOR_GREEN,
                fields=[],
                footer_text="Generated by PM Operations Agent"
            )

        title = f"⚠️ {team_name} — PM Attention Digest"
        sections = []

        # 1. Inactive / Stalled
        stale_info = categories.get("inactive_stalled", {})
        stale_tickets = stale_info.get("tickets", [])
        if stale_tickets:
            stale_title = stale_info.get("title", "🟠 Inactive / Stalled")
            col_ticket_w = max(11, max((len(t.get("key", "")) for t in stale_tickets), default=11))
            col_status_w = max(11, max((len(t.get("status", "")) for t in stale_tickets), default=11))
            col_updated_w = 12
            col_inactive_w = 12

            header_line = f"| {'Ticket':<{col_ticket_w}} | {'Status':<{col_status_w}} | {'Last Updated':<{col_updated_w}} | {'Inactive For':<{col_inactive_w}} |"
            sep_line = f"| {'-' * col_ticket_w} | {'-' * col_status_w} | {'-' * col_updated_w} | {'-' * col_inactive_w} |"

            table_lines = [f"`{header_line}`", f"`{sep_line}`"]
            for t in stale_tickets:
                tkey = t.get("key", "Unknown")
                jira_url = t.get("url") or settings.get_jira_browse_url(tkey)
                status_str = t.get("status", "Unknown")
                upd_str = t.get("updated_at", "—")
                inactive_str = t.get("inactive_for", "—")
                pad_ticket = " " * max(0, col_ticket_w - len(tkey))
                row = f"`| `[{tkey}]({jira_url})`{pad_ticket} | {status_str:<{col_status_w}} | {upd_str:<{col_updated_w}} | {inactive_str:<{col_inactive_w}} |`"
                table_lines.append(row)

            sections.append(f"{stale_title}\n\n" + "\n".join(table_lines))

        # 2. Reopened
        reopened_info = categories.get("reopened", {})
        reopened_tickets = reopened_info.get("tickets", [])
        if reopened_tickets:
            reopened_title = reopened_info.get("title", "🔁 Reopened")
            col_ticket_w = max(11, max((len(t.get("key", "")) for t in reopened_tickets), default=11))
            col_status_w = max(11, max((len(t.get("status", "")) for t in reopened_tickets), default=11))
            col_updated_w = 12

            header_line = f"| {'Ticket':<{col_ticket_w}} | {'Status':<{col_status_w}} | {'Last Updated':<{col_updated_w}} |"
            sep_line = f"| {'-' * col_ticket_w} | {'-' * col_status_w} | {'-' * col_updated_w} |"

            table_lines = [f"`{header_line}`", f"`{sep_line}`"]
            for t in reopened_tickets:
                tkey = t.get("key", "Unknown")
                jira_url = t.get("url") or settings.get_jira_browse_url(tkey)
                status_str = t.get("status", "Unknown")
                upd_str = t.get("updated_at", "—")
                pad_ticket = " " * max(0, col_ticket_w - len(tkey))
                row = f"`| `[{tkey}]({jira_url})`{pad_ticket} | {status_str:<{col_status_w}} | {upd_str:<{col_updated_w}} |`"
                table_lines.append(row)

            sections.append(f"{reopened_title}\n\n" + "\n".join(table_lines))

        # 3. Unassigned
        unassigned_info = categories.get("unassigned", {})
        unassigned_tickets = unassigned_info.get("tickets", [])
        if unassigned_tickets:
            unassigned_title = unassigned_info.get("title", "📌 Unassigned")
            col_ticket_w = max(11, max((len(t.get("key", "")) for t in unassigned_tickets), default=11))
            col_status_w = max(11, max((len(t.get("status", "")) for t in unassigned_tickets), default=11))
            col_updated_w = 12

            header_line = f"| {'Ticket':<{col_ticket_w}} | {'Status':<{col_status_w}} | {'Last Updated':<{col_updated_w}} |"
            sep_line = f"| {'-' * col_ticket_w} | {'-' * col_status_w} | {'-' * col_updated_w} |"

            table_lines = [f"`{header_line}`", f"`{sep_line}`"]
            for t in unassigned_tickets:
                tkey = t.get("key", "Unknown")
                jira_url = t.get("url") or settings.get_jira_browse_url(tkey)
                status_str = t.get("status", "Unknown")
                upd_str = t.get("updated_at", "—")
                pad_ticket = " " * max(0, col_ticket_w - len(tkey))
                row = f"`| `[{tkey}]({jira_url})`{pad_ticket} | {status_str:<{col_status_w}} | {upd_str:<{col_updated_w}} |`"
                table_lines.append(row)

            sections.append(f"{unassigned_title}\n\n" + "\n".join(table_lines))

        body = "\n\n".join(sections)
        description = f"**Date:** {date_str}\n\n{body}"

        return cls.format_embed(
            title=title,
            description=description,
            color=COLOR_AMBER,
            fields=[],
            footer_text="Generated by PM Operations Agent"
        )

    @classmethod
    def format_pm_attention_text(cls, report_data: Dict[str, Any]) -> str:
        """Format PM attention digest into plain Discord markdown text for slash commands."""
        team_name = report_data.get("team_name") or "Team"
        date_str = report_data.get("date") or report_data.get("formatted_date") or "Today"
        total_count = report_data.get("total_count", 0)
        categories = report_data.get("categories", {})

        if total_count == 0:
            return (
                f"✅ **{team_name} — PM Attention Digest**\n"
                f"**Date:** {date_str}\n\n"
                f"No items requiring attention.\n\n"
                f"──────────────────────────────────────────────────\n"
                f"*Generated by PM Operations Agent*"
            )

        sections = []
        # 1. Inactive / Stalled
        stale_info = categories.get("inactive_stalled", {})
        stale_tickets = stale_info.get("tickets", [])
        if stale_tickets:
            stale_title = stale_info.get("title", "🟠 Inactive / Stalled")
            col_ticket_w = max(11, max((len(t.get("key", "")) for t in stale_tickets), default=11))
            col_status_w = max(11, max((len(t.get("status", "")) for t in stale_tickets), default=11))
            col_updated_w = 12
            col_inactive_w = 12

            header_line = f"| {'Ticket':<{col_ticket_w}} | {'Status':<{col_status_w}} | {'Last Updated':<{col_updated_w}} | {'Inactive For':<{col_inactive_w}} |"
            sep_line = f"| {'-' * col_ticket_w} | {'-' * col_status_w} | {'-' * col_updated_w} | {'-' * col_inactive_w} |"

            table_lines = [f"`{header_line}`", f"`{sep_line}`"]
            for t in stale_tickets:
                tkey = t.get("key", "Unknown")
                jira_url = t.get("url") or settings.get_jira_browse_url(tkey)
                status_str = t.get("status", "Unknown")
                upd_str = t.get("updated_at", "—")
                inactive_str = t.get("inactive_for", "—")
                pad_ticket = " " * max(0, col_ticket_w - len(tkey))
                row = f"`| `[{tkey}]({jira_url})`{pad_ticket} | {status_str:<{col_status_w}} | {upd_str:<{col_updated_w}} | {inactive_str:<{col_inactive_w}} |`"
                table_lines.append(row)

            sections.append(f"**{stale_title}**\n\n" + "\n".join(table_lines))

        # 2. Reopened
        reopened_info = categories.get("reopened", {})
        reopened_tickets = reopened_info.get("tickets", [])
        if reopened_tickets:
            reopened_title = reopened_info.get("title", "🔁 Reopened")
            col_ticket_w = max(11, max((len(t.get("key", "")) for t in reopened_tickets), default=11))
            col_status_w = max(11, max((len(t.get("status", "")) for t in reopened_tickets), default=11))
            col_updated_w = 12

            header_line = f"| {'Ticket':<{col_ticket_w}} | {'Status':<{col_status_w}} | {'Last Updated':<{col_updated_w}} |"
            sep_line = f"| {'-' * col_ticket_w} | {'-' * col_status_w} | {'-' * col_updated_w} |"

            table_lines = [f"`{header_line}`", f"`{sep_line}`"]
            for t in reopened_tickets:
                tkey = t.get("key", "Unknown")
                jira_url = t.get("url") or settings.get_jira_browse_url(tkey)
                status_str = t.get("status", "Unknown")
                upd_str = t.get("updated_at", "—")
                pad_ticket = " " * max(0, col_ticket_w - len(tkey))
                row = f"`| `[{tkey}]({jira_url})`{pad_ticket} | {status_str:<{col_status_w}} | {upd_str:<{col_updated_w}} |`"
                table_lines.append(row)

            sections.append(f"**{reopened_title}**\n\n" + "\n".join(table_lines))

        # 3. Unassigned
        unassigned_info = categories.get("unassigned", {})
        unassigned_tickets = unassigned_info.get("tickets", [])
        if unassigned_tickets:
            unassigned_title = unassigned_info.get("title", "📌 Unassigned")
            col_ticket_w = max(11, max((len(t.get("key", "")) for t in unassigned_tickets), default=11))
            col_status_w = max(11, max((len(t.get("status", "")) for t in unassigned_tickets), default=11))
            col_updated_w = 12

            header_line = f"| {'Ticket':<{col_ticket_w}} | {'Status':<{col_status_w}} | {'Last Updated':<{col_updated_w}} |"
            sep_line = f"| {'-' * col_ticket_w} | {'-' * col_status_w} | {'-' * col_updated_w} |"

            table_lines = [f"`{header_line}`", f"`{sep_line}`"]
            for t in unassigned_tickets:
                tkey = t.get("key", "Unknown")
                jira_url = t.get("url") or settings.get_jira_browse_url(tkey)
                status_str = t.get("status", "Unknown")
                upd_str = t.get("updated_at", "—")
                pad_ticket = " " * max(0, col_ticket_w - len(tkey))
                row = f"`| `[{tkey}]({jira_url})`{pad_ticket} | {status_str:<{col_status_w}} | {upd_str:<{col_updated_w}} |`"
                table_lines.append(row)

            sections.append(f"**{unassigned_title}**\n\n" + "\n".join(table_lines))

        body = "\n\n".join(sections)
        return (
            f"⚠️ **{team_name} — PM Attention Digest**\n"
            f"**Date:** {date_str}\n\n"
            f"{body}\n\n"
            f"──────────────────────────────────────────────────\n"
            f"*Generated by PM Operations Agent*"
        )

    @classmethod
    def format_user_mapping_required(
        cls,
        jira_user_name: str,
        jira_user_id: str,
        intended_action: str,
        timestamp: Optional[str] = None
    ) -> Dict[str, Any]:
        """Format an alert when user mapping is missing for a direct message."""
        fields = [
            {"name": "Jira User", "value": f"{jira_user_name} (`{jira_user_id}`)", "inline": False},
            {"name": "Intended Action", "value": intended_action, "inline": False},
            {"name": "Status", "value": "❌ Direct Message was NOT sent.", "inline": False},
        ]
        return cls.format_embed(
            title="⚠️ Mattermost Mapping Required",
            description="No verified Mattermost account mapping exists for this resource. Please create a mapping in the database.",
            color=COLOR_AMBER,
            fields=fields,
            timestamp=timestamp
        )

    @classmethod
    def format_daily_report(cls, report_data: Dict[str, Any]) -> Dict[str, Any]:
        """Format daily activity report into a rich Discord embed."""
        date_str = report_data.get("date", "Today")
        total_activities = report_data.get("total_activities", 0)
        tasks_created = report_data.get("tasks_created", 0)
        tasks_completed = report_data.get("tasks_completed", 0)
        transitions = report_data.get("status_transitions", 0)
        comments = report_data.get("comments_added", 0)
        worklogs = report_data.get("worklogs_logged", 0)
        violations = report_data.get("workflow_violations", 0)
        stale_count = report_data.get("stale_tasks", 0)

        fields = [
            {"name": "📊 Total Activities", "value": str(total_activities), "inline": True},
            {"name": "✨ Tasks Created", "value": str(tasks_created), "inline": True},
            {"name": "✅ Tasks Completed", "value": str(tasks_completed), "inline": True},
            {"name": "🔄 Status Transitions", "value": str(transitions), "inline": True},
            {"name": "💬 Comments Added", "value": str(comments), "inline": True},
            {"name": "⏱️ Worklogs Logged", "value": str(worklogs), "inline": True},
            {"name": "🚨 Workflow Violations", "value": str(violations), "inline": True},
            {"name": "⚠️ Stale Tasks", "value": str(stale_count), "inline": True},
        ]

        by_resource = report_data.get("activities_by_resource", {})
        if by_resource:
            res_summary = "\n".join([f"• **{name}**: {count} activities" for name, count in by_resource.items()])
            fields.append({"name": "👥 Activities by Resource", "value": res_summary[:1000], "inline": False})

        return cls.format_embed(
            title=f"📋 Daily PM Activity Report — {date_str}",
            description=f"Summary of all project activities and automated workflow rules for {date_str}.",
            color=COLOR_PURPLE,
            fields=fields,
            footer_text="Generated by PM Operations Agent"
        )

    @classmethod
    def format_daily_report_text(cls, report_data: Dict[str, Any]) -> str:
        """Format daily activity report into plain Discord markdown text for slash commands."""
        date_str = report_data.get("date", "Today")
        total_activities = report_data.get("total_activities", 0)
        tasks_created = report_data.get("tasks_created", 0)
        tasks_completed = report_data.get("tasks_completed", 0)
        transitions = report_data.get("status_transitions", 0)
        comments = report_data.get("comments_added", 0)
        worklogs = report_data.get("worklogs_logged", 0)
        violations = report_data.get("workflow_violations", 0)
        stale_count = report_data.get("stale_tasks", 0)

        res_lines = []
        by_resource = report_data.get("activities_by_resource", {})
        if by_resource:
            res_lines.append("\n👥 **Activities by Resource**:")
            for name, count in by_resource.items():
                res_lines.append(f"• **{name}**: {count} activities")
        res_str = "\n".join(res_lines)

        return (
            f"📋 **Daily PM Activity Report — {date_str}**\n"
            f"Summary of all project activities and automated workflow rules for {date_str}.\n\n"
            f"• 📊 **Total Activities**: {total_activities}\n"
            f"• ✨ **Tasks Created**: {tasks_created}\n"
            f"• ✅ **Tasks Completed**: {tasks_completed}\n"
            f"• 🔄 **Status Transitions**: {transitions}\n"
            f"• 💬 **Comments Added**: {comments}\n"
            f"• ⏱️ **Worklogs Logged**: {worklogs}\n"
            f"• 🚨 **Workflow Violations**: {violations}\n"
            f"• ⚠️ **Stale Tasks**: {stale_count}"
            f"{res_str}\n\n"
            f"──────────────────────────────────────────────────\n"
            f"*Generated by PM Operations Agent*"
        )

    @classmethod
    def format_user_worklog_text(cls, report_data: Dict[str, Any]) -> str:
        """Format individual-resource daily worklog into clean monospace Discord markdown table."""
        display_name = report_data.get("display_name", "Resource")
        date_str = report_data.get("date", "Today")
        total_time = report_data.get("total_time_human", "0m")
        tickets = report_data.get("tickets", [])

        header = f"📊 **Daily Worklog — {display_name}**\n**Date:** {date_str}\n\n"

        if not tickets:
            return (
                f"{header}"
                f"No worklogs logged for {display_name} on {date_str}.\n\n"
                f"**Total:** {total_time}\n\n"
                f"──────────────────────────────────────────────────\n"
                f"*Generated by PM Operations Agent*"
            )

        table_lines = [
            "`| Ticket      | Time Logged |`",
            "`|-------------|------------:|`",
        ]
        for t in tickets:
            tkey = t.get("key", "Unknown")
            time_h = t.get("time_logged_human", "0m")
            url = t.get("url") or settings.get_jira_browse_url(tkey)
            pad_key = " " * max(0, 11 - len(tkey))
            pad_time = " " * max(0, 11 - len(time_h))
            table_lines.append(f"`| `[{tkey}]({url})`{pad_key} | {pad_time}{time_h} |`")

        table_str = "\n".join(table_lines)
        return (
            f"{header}"
            f"{table_str}\n\n"
            f"**Total:** {total_time}\n\n"
            f"──────────────────────────────────────────────────\n"
            f"*Generated by PM Operations Agent*"
        )

    @classmethod
    def format_user_overdue_digest_text(cls, digest_data: Dict[str, Any]) -> str:
        """Format individual-resource overdue digest into clean monospace Discord markdown table."""
        display_name = digest_data.get("display_name", "Resource")
        date_str = digest_data.get("date", "Today")
        tickets = digest_data.get("tickets", [])

        header = f"📋 **Overdue Tasks — {display_name}**\n**Date:** {date_str}\n\n"

        if not tickets:
            return (
                f"{header}"
                f"No overdue tasks found for {display_name}.\n\n"
                f"──────────────────────────────────────────────────\n"
                f"*Generated by PM Operations Agent*"
            )

        table_lines = [
            "`| Ticket      | Assignee             | Due Date   | Last Updated     |`",
            "`|-------------|----------------------|------------|------------------|`",
        ]
        for t in tickets:
            tkey = t.get("key", "Unknown")
            assignee = t.get("assignee") or display_name or "—"
            due_date = t.get("due_date", "—")
            updated_at = t.get("updated_at", "—")
            url = t.get("url") or settings.get_jira_browse_url(tkey)

            pad_key = " " * max(0, 11 - len(tkey))
            pad_ass = " " * max(0, 20 - cls._get_visual_length(assignee))
            pad_due = " " * max(0, 10 - len(due_date))
            pad_upd = " " * max(0, 16 - len(updated_at))

            table_lines.append(
                f"`| `[{tkey}]({url})`{pad_key} | {assignee}{pad_ass} | {due_date}{pad_due} | {updated_at}{pad_upd} |`"
            )

        table_str = "\n".join(table_lines)
        return (
            f"{header}"
            f"**Total Overdue:** {len(tickets)}\n\n"
            f"{table_str}\n\n"
            f"──────────────────────────────────────────────────\n"
            f"*Generated by PM Operations Agent*"
        )

    @classmethod
    def format_user_active_queue_text(cls, queue_data: Dict[str, Any]) -> str:
        """Format individual-resource active queue into clean monospace Discord markdown table."""
        display_name = queue_data.get("display_name", "Resource")
        date_str = queue_data.get("date", "Today")
        tickets = queue_data.get("tickets", [])
        active_count = queue_data.get("active_count", len(tickets))

        header = f"📌 **Active Queue — {display_name}**\n**Date:** {date_str}\n\n"

        if not tickets:
            return (
                f"{header}"
                f"No active tasks in queue for {display_name}.\n\n"
                f"**Total Active:** 0\n\n"
                f"──────────────────────────────────────────────────\n"
                f"*Generated by PM Operations Agent*"
            )

        table_lines = [
            "`| Ticket      | Summary                        | Status      | Priority | Due Date   |`",
            "`|-------------|--------------------------------|-------------|----------|------------|`",
        ]
        for t in tickets:
            tkey = t.get("key", "Unknown")
            summary = (t.get("summary") or "Untitled")[:30]
            status = (t.get("status") or "To Do")[:11]
            priority = (t.get("priority") or "Medium")[:8]
            due_date = t.get("due_date", "—")
            url = t.get("url") or settings.get_jira_browse_url(tkey)

            pad_key = " " * max(0, 11 - len(tkey))
            pad_sum = " " * max(0, 30 - cls._get_visual_length(summary))
            pad_stat = " " * max(0, 11 - cls._get_visual_length(status))
            pad_prio = " " * max(0, 8 - cls._get_visual_length(priority))
            pad_due = " " * max(0, 10 - len(due_date))

            table_lines.append(
                f"`| `[{tkey}]({url})`{pad_key} | {summary}{pad_sum} | {status}{pad_stat} | {priority}{pad_prio} | {due_date}{pad_due} |`"
            )

        table_str = "\n".join(table_lines)
        return (
            f"{header}"
            f"{table_str}\n\n"
            f"**Total Active:** {active_count}\n\n"
            f"──────────────────────────────────────────────────\n"
            f"*Generated by PM Operations Agent*"
        )

    @classmethod
    def format_ticket_creation_notification(
        cls,
        task_key: str,
        summary: str,
        creator_name: str,
        issue_type: str,
        project_key: str,
        created_at: Optional[str] = None,
        policy_classification: str = "REVIEW",
        policy_reason: str = "",
    ) -> Dict[str, Any]:
        """Format instant Jira ticket creation alert as a prominent Discord embed with dark pink/red accent."""
        from app.core.reports.overdue_report import format_jira_updated_at
        created_display = format_jira_updated_at(created_at) if created_at else "Just now"
        url = settings.get_jira_browse_url(task_key)

        is_expected = policy_classification.upper() == "EXPECTED"
        title = f"🚨 Ticket Created — Expected" if is_expected else "⚠️ Ticket Created — Review"

        fields = [
            {"name": "🎫 Ticket", "value": f"[{task_key}]({url})", "inline": True},
            {"name": "👤 Created by", "value": creator_name, "inline": True},
            {"name": "🏷️ Type", "value": issue_type, "inline": True},
            {"name": "📁 Project", "value": project_key, "inline": True},
            {"name": "🕒 Created", "value": created_display, "inline": True},
            {"name": "📝 Summary", "value": summary[:500] if summary else "Untitled", "inline": False},
            {"name": "🛡️ Policy", "value": f"**{policy_classification.upper()}** — {policy_reason}", "inline": False},
        ]

        return cls.format_embed(
            title=title,
            description=f"Ticket creation event detected on project **{project_key}**.",
            color=COLOR_DARK_PINK,
            fields=fields,
            footer_text="Generated by PM Operations Agent",
            url=url,
        )

